### ISSUE TITLE
Add support for python 2

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#10]

**Comment by relekang** [comment]
Releated: #9

**Comment by relekang** [comment]
Benefit: be to be able to use the setup.py hook in python 2 projects

**Comment by relekang** [comment]
[Should avoid this](https://ci.frigg.io/relekang/django-nopassword/70/)

**Comment by jezdez** [comment]
Yeah, I'd vote for Python 2 support. I'm happy to provide a patch if you'd like.

**Comment by relekang** [comment]
Yeah, that would be great.

**Comment by jezdez** [comment]
Cool! Will do this week :)

**Comment by relekang** [comment]
Sweet, I think a27e282 removes all usage of python 3 only features from configparser :)
