### ISSUE TITLE
Install requirements are frozen to exact versions

### ISSUE THREAD

**Issue by jensgustafsson** [relekang/python-semantic-release#100]
Most of the install requirements for this package are frozen to exact versions:

`requirements/base.txt`:

```
click==6.2
gitpython==2.1.10
invoke==0.11.1
semver==2.2.1
twine==1.12.1
requests>=2.9.1<3
wheel
```

This makes it hard to use this package together with your own python package.

If you for instance have a requirement on `click` in your own python package, you must use `click==6.2.0`, even though
there exists newer versions.

I think the requirements should be semantic instead:

```
click>=6.2<7
```

My way of solving this problem atm is to create a separate venv where I install `python-semantic-release` but it would simplify our CI process if we could install this package together with our other packages.

**Comment by relekang** [comment]
👍 Happy to accept pr for this, but I think the packages with major version 0 needs to be pinned.

**Comment by relekang** [comment]
I disagree with that, the dev environment should reflect the install environment as much as possible. Making this information stored two places will end up with an upgrade be done in only one place at some point.
