### ISSUE TITLE
python-semantic-release should have an option to pull version_variable from git tag

### ISSUE THREAD

**Issue by mmacvicar-splunk** [relekang/python-semantic-release#104]
python-semantic-release should have an option to pull version_variable from git tag

python-semantic-release requires version_variable to be in a file and bumps and auto-commits it.

For parity with semantic-release per https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository semantic release updates package.json then prepares and publishes the package and doesn't auto-commit the version change. 

This is desirable for CI so that auto-commits don't require troublesome exceptions to prevent an infinite loop of version bumps.

If we don’t push the commit to the version_variable subsequent runs report the following error
```$ semantic-release version --patch
Creating new version..
Current version: 0.0.0
Cmd('git') failed due to: exit code(128)
  cmdline: git tag -m v0.0.1 -a v0.0.1
  stderr: 'fatal: tag 'v0.0.1' already exists'
```

**Comment by relekang** [comment]
I guess I would not object a pr that adds this as an option, but current behaviour should be left as default.

**Comment by fattybenji** [comment]
@mmacvicar-splunk I'm currently working on #119 so I will be doing some work on this part of the code, namely the files used to get/set the version. Could you please explain your issue in more details ?

From what I gather reading the code, the current version can be obtained from git if `semantic.version_source` is `"tag"`. The version is set in `set_new_version` but only commited if `version_source` is `"commit"`.

It looks like overriding `version_source` with the value `tag` in the setup.cfg of your project might suit your need, but I might have missed something.

**Comment by fattybenji** [comment]
I think I understand what you mean. Just to be sure :

### Current behavior

* If `version_source` is `commit`, will get version from `version_variable` file, edit the file and commit it.
* If `version_source` is `tag`, will get version from VCS and won't edit the file.

### Requested behavior

* If `version_source` is `commit`, no change.
* If `version_source` is `tag`, will get version from VCS and will edit the `version_variable` file.

However, @relekang wants to keep the current behavior of the `tag` option.

For me there are two options :

* adding a new possible value to `version_source` (for example `tag_and_commit`, I'm open to suggestions) that would get from VCS and edit/commit the `version_variable` file.
* adding a new boolean configuration key, for example `commit_changes`, that would default to `false` and be used only in the case of the `tag` option.

What do you think ?

**Comment by mmacvicar-splunk** [comment]
Yes, you have it correct. 

Of the top of my head, my solution would be if you specify `version_source` and `version_variable` it will generate a new version based on `version_source` and write it to `version_variable`. In addition, any time `version_variable` is specified, it would write to that variable. 

`commit_changes` would be nice to have, as I can choose not to push commits, maybe it should default to true to preserve backward functionality.

Example setup.cfg
```
[semantic_release]
version_source=tag
version_variable=version.py:__version__
```

**Comment by fattybenji** [comment]
Ok, I'm going to do the following :

* If `version_source` is `commit`, will get version from `version_variable` file and edit the file with the new  version. If variable `commit_changes` is defined and `False`, won't commit. If it is undefined or `True`, will commit and push changes.
* If `version_source` is `tag`, will get version from VCS and will edit the file defined in `version_variable`. If the file doesn't exist, will fail silently (backwards compatibility). If variable `commit_changes` is defined and `True`, will commit and push changes. If it is undefined or `False`, won't push.

I intend to do that by setting the actual value of `commit_changes` as :

```
commit_changes = config.get('semantic_release', 'commit_changes', fallback=(version_source == 'commit'))
```

This way, we will have a full backward compatibility with the current behavior, while giving people the choice to do differently. This can be discussed when I submit the PR.

**Comment by fattybenji** [comment]
Renamed `commit_changes` to `commit_version_number`

See https://github.com/relekang/python-semantic-release/pull/143#pullrequestreview-283235383
