### ISSUE TITLE
Full functionality without remote

### ISSUE THREAD

**Issue by emKaroly** [relekang/python-semantic-release#116]
Hi Guys. Nice work. 
I tried this tool and it is working nicely. I would like to use this tool in all my projects but i have some issues.

Usually i have nothing to do with Python projects, mostly i am doing c++ and android but i think its doable.
So the problem is now if i do publish it says "Remote named 'origin' didn't exist"
It is possible to make it work without remote so only in local repo and write the changelog to local file?
Because thats everything i need to make it work in any project not only python.
Thank you.

**Comment by relekang** [comment]
Can be added with a flag `use_remote_version_control` that should be true as default. See `upload_to_pypi`([see docs](https://github.com/relekang/python-semantic-release/blob/master/docs/configuration.rst)) flag in the config file.

**Comment by laercio-barbosa** [comment]
Hi @relekang 

Is this `use_remote_version_control` feature still on the roadmap? Or is there another way to get the same result: only perform changes in local repo?
I have tried `--noop` option, but it does no operation at all.
