### ISSUE TITLE
Upgrade to click ^7.0

### ISSUE THREAD

**Issue by jasonkuhrt** [relekang/python-semantic-release#117]
It would seem that when using python-semantic-release in a project, click v7 cannot be used.

```
❯ poetry add click
Using version ^7.0 for click

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
Because no versions of python-semantic-release match >4.1,<4.1.1 || >4.1.1,<5.0
 and python-semantic-release (4.1.1) depends on click (>=6.2,<7.0), python-semantic-release (>4.1,<5.0) requires click (>=6.2,<7.0).
And because python-semantic-release (4.1.0) depends on click (>=6.2,<7.0), python-semantic-release (>=4.1,<5.0) requires click (>=6.2,<7.0).
So, because mano depends on both click (^7.0) and python-semantic-release (^4.1), version solving failed.
```

Consider this a feature request to have `python-semantic-release` upgrade to `^7.0` of `click`.

**Comment by relekang** [comment]
Happy to accept a pr for this.

**Comment by openbrian** [comment]
I was just thinking about this.  Does this project really need click 7.0?  If not we should not require ~7.0.  In fact, I suspect version 2.0 is enough.  I downgraded and all tests pass.  (I mean all tests that were passing before continue to pass.  There are 2 which are expected to fail.)  I set requirements/base.txt to click>=2.0.
