### ISSUE TITLE
--version-variable flag alternative to cfg file

### ISSUE THREAD

**Issue by jasonkuhrt** [relekang/python-semantic-release#119]
When encapsulating release into a reusable ci-cd pipeline component (e.g. CircleCI orbs) it can be nice to automate some config for the project. Currently `version_variable` must be set in `setup.cfg` (it seems). It would be great if it can also be passed as a cli flag.

The workaround is to run file manipulations withi the ci-cd job to maipulate `setup.cfg` as needed.

**Comment by Azraeht** [comment]
Something great should be to make python-semantic-release able to work with setup.cfg and pyproject.toml.

This could allow to read/write automatically the new version within the right configuration file.
It could allow to completely automated the CD process of a lib.

Something such as:
* Get the new version from vcs history (already exists)
* Bump it and write it in setup.cfg, pyproject.yml or __init__.py
* Create a new commit for this change, create the new tag on it

At Sewan we will setup this feature and submit a PR from our fork https://github.com/Azraeht/python-semantic-release

**Comment by fattybenji** [comment]
Taking this one in https://github.com/SewanDevs/python-semantic-release

**Comment by fattybenji** [comment]
For this issue, I will concentrate on having a way to overload configuration using cli, and I will add pyproject.toml as a source for configuration keys.

The other issues mentioned by Azraeht will probably be adressed in another issue.

**Comment by fattybenji** [comment]
I added a `-D` or `--define` option that allows the overriding of the configuration. This option works the same way as defined in sonar-scanner or sphinx-build :

https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
https://www.sphinx-doc.org/en/master/man/sphinx-build.html

**Comment by relekang** [comment]
@fattybenji Sounds like a good solution 👍
