### ISSUE TITLE
What should the default version-level tags be?

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#12]
Currently they are:
- **Major change:** `major_tag = :boom:` :boom:
- **Minor change:** `minor_tag = :sparkles:` :sparkles:
- **Patch change:** `patch_tag = :bug:` :bug:

**Comment by jezdez** [comment]
Paging the resident emoji expert @bmispelon..

**Comment by bmispelon** [comment]
Major: :guardsman: 
Minor: :underage: 
Patch: :nut_and_bolt:

**Comment by relekang** [comment]
All for :guardsman:  and :nut_and_bolt: , but I think :underage: might be better for beta releases?

**Comment by mauricioabreu** [comment]
lol, I like @bmispelon idea :-)

**Comment by relekang** [comment]
#21 changes the behaviour of the version detection, and makes this issue not as relevant. However, we can always add an "emoji parser" :)
