### ISSUE TITLE
publish creates incomplete Breaking section

### ISSUE THREAD

**Issue by daveenguyen** [relekang/python-semantic-release#120]
The breaking section of published github release results in weird outputs.

```
### Feature
* Delete AXKeyCodeConstants (6b214305f65e38e941203fb47ca4990af67f4b7f)
* delete Clipboard and Prefs (378a66cf54bea5f554b996adec9ec1b06a5e136d)

### Breaking
* e (D)
* o (M)
```

The two commits are supposed to be
https://github.com/daveenguyen/atomacos/commit/6b214305f65e38e941203fb47ca4990af67f4b7f
https://github.com/daveenguyen/atomacos/commit/378a66cf54bea5f554b996adec9ec1b06a5e136d

**Comment by relekang** [comment]
Thanks for reporting this.
