### ISSUE TITLE
Support for publishing changelogs to gitlab

### ISSUE THREAD

**Issue by dcs3spp** [relekang/python-semantic-release#121]
Hi,

I have a project on gitlab and have been trying out python-semantic-release. I have managed to use python-semantic-release to bump version and create tag on remote repository.

```
semantic-release publish
                                      
Current version: 1.4.0
Creating new version..
Current version: 1.4.0
Bumping with a minor version to 1.5.0.
Missing token: cannot post changelog
New release published
```

However, the changelog is not pushed. Based on, [semantic-release] (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration) documentation I have tried setting environment variables GL_TOKEN and GITLAB_TOKEN. However,  these do not seem to be recognised.

What is the environment variable required for gitlab repositories? Is publishing changelog only possible for github repositories?

Kind regards

dcs3spp

**Comment by relekang** [comment]
Publishing of changelog is only implemented for github. PR for gitlab support is more than welcome.

**Comment by Azraeht** [comment]
Hello!

At Sewan we also have this need. We will develop this features and create a PR for you on this topic form : https://github.com/Azraeht/python-semantic-release

**Comment by fattybenji** [comment]
I will be working on this in https://github.com/SewanDevs/python-semantic-release.

I will try to make the library more compliant with gitlab in general. For example, the method `vcs_helpres.push_new_version` contains github specific code. This could be moved in the Github class in `hvcs.py`.

**Comment by fattybenji** [comment]
@dcs3spp just opened a pull request. This will allow the publishing of changelogs on gitlab.com and Gitlab CE (probably EE too, but I did not test it on EE).

Once this is released, you will need to set a gitlab token as `GL_TOKEN`, change the `hvcs` configuration key and if you are on a hosted gitlab instance (not gitlab.com), you will need to set `CI_SERVER_HOST` unless you are in a gitlab ci environment where it is automatically set.

This is normally described in the updated documentation.
