### ISSUE TITLE
Circle CI not building on pull requests?

### ISSUE THREAD

**Issue by esciara** [relekang/python-semantic-release#126]
Hi,

Looks like Circle CI is not building on pull requests, like on [this pull request](https://github.com/relekang/python-semantic-release/pull/125):

<img width="783" alt="Capture d’écran 2019-06-04 à 14 46 06" src="https://user-images.githubusercontent.com/1336689/58880147-88a33a00-86d7-11e9-9c21-bcc8c2310e55.png">

Maybe the ["Build forked pull requests"](https://circleci.com/docs/2.0/oss/#only-build-pull-requests) option is not set?

Em

**Comment by relekang** [comment]
Weird, it has been working for the other pull-requests. 🤔

**Comment by esciara** [comment]
Hmm... don't think I did anything out of the norm... forked the repo, created a branch, created a pull request from the branch using GitHub's interface...

**Comment by esciara** [comment]
Same problem with new pull request https://github.com/relekang/python-semantic-release/pull/128

**Comment by esciara** [comment]
Aha! It started working after I pushed some new changes. So it does not appear to work when creating a PR but does on new commits on the PR...

**Comment by relekang** [comment]
This worked as expected on the last PR.
