### ISSUE TITLE
Dev requirements need cleaning

### ISSUE THREAD

**Issue by esciara** [relekang/python-semantic-release#127]
Can see several issues that could lead to different behaviors depending where the various verifications are run, for instance:

 * `tox` version is [fixed to 2.3.1](https://github.com/relekang/python-semantic-release/blob/fb7bb14300e483626464795b8ff4f033a194cf6f/requirements/dev.txt#L8) in `dev.txt` requirements, whereas it does [not have any version fixed](https://github.com/relekang/python-semantic-release/blob/fb7bb14300e483626464795b8ff4f033a194cf6f/.circleci/config.yml#L10) in `.circleci/config.yml`.
* same for [`mypy` in `dev.txt`](https://github.com/relekang/python-semantic-release/blob/fb7bb14300e483626464795b8ff4f033a194cf6f/requirements/dev.txt#L11) and in [`tox.ini`](https://github.com/relekang/python-semantic-release/blob/fb7bb14300e483626464795b8ff4f033a194cf6f/tox.ini#L16)
* isort is not in `dev.txt` but used in [`tox.ini`](https://github.com/relekang/python-semantic-release/blob/fb7bb14300e483626464795b8ff4f033a194cf6f/tox.ini#L26) and [is run in `circleci`](https://github.com/relekang/python-semantic-release/blob/fb7bb14300e483626464795b8ff4f033a194cf6f/.circleci/config.yml#L80).
*...

It all needs a clean up.

**Comment by esciara** [comment]
Working on a PR for this.

**Comment by relekang** [comment]
I don't think tox needs to be pinned, maybe unpin it in dev.txt?

**Comment by esciara** [comment]
Will look at it over the weekend.

**Comment by esciara** [comment]
Also for readability I will be cleaning the `tox.ini` file so that it uses classical [tox environment settings](https://tox.readthedocs.io/en/latest/config.html#tox-environment-settings) instead of [factors and factor-conditional settings](https://tox.readthedocs.io/en/latest/config.html#factors-and-factor-conditional-settings), as there is no real need for it.

I will also reorder their declaration according to the order of the CircleCI config file.

**Comment by relekang** [comment]
I moved a few things from dev.txt to tools.txt, so they don't get installed in the test tox env.
