### ISSUE TITLE
Add commit message tools and pre-commit hooks to ensure QA before running CI

### ISSUE THREAD

**Issue by esciara** [relekang/python-semantic-release#132]
Installing and using [`pre-commit`](https://pre-commit.com) as used by [`tox` team](https://github.com/tox-dev/tox/blob/master/.pre-commit-config.yaml) and others, would allow people to have QA checked before submitting work and wasting some CI time and resources.

Also, using python's version of [`commitizen`](https://woile.github.io/commitizen/) would help writing commits to harness the power of `python-semantic-release`.

Lastly, using [`gitlint`](http://jorisroovers.github.io/gitlint/) as a pre-push hook would ensure that no commit is pushed that cannot be used by `python-semantic-release`.

Note: tests will not be able to be run as pre-commit hooks until #131 / #108 are fixed.

**Comment by esciara** [comment]
This article on [`pre-commit`](https://blog.jerrycodes.com/pre-commit-is-awesome/) is interesting.

**Comment by relekang** [comment]
You are free to setup hooks in your own clone. I don't think we should enforce commit hooks on everyone.

**Comment by esciara** [comment]
Sure, as you wish.
