### ISSUE TITLE
semantic-release changelog before semantic-release --noop version

### ISSUE THREAD

**Issue by mouadhkaabachi** [relekang/python-semantic-release#134]
Hi,
Thank you for the python-semantic-release project,
I noticed that when I use `semantic-release changelog` to generate changelogs (after creating many commits) and  **before bumping new version with** `semantic-release --noop version` , python-semantic-release will not show changelogs,
I want to know if it's possible de generate changelogs with `semantic-release changelog` before bumping new version with `semantic-release --noop version`

**Comment by relekang** [comment]
Open to PRs for showing unreleased things in the changelog with a flag `--unreleased` to the changelog command.
