### ISSUE TITLE
Implement the use of exclamation points to describe breaking changes

### ISSUE THREAD

**Issue by fattybenji** [relekang/python-semantic-release#156]
According to https://www.conventionalcommits.org/en/v1.0.0/ , a breaking change can be described by using an exclamation point. Here are three cases that will generate the same major version bump and the same breaking change message.

Case 1 :
```
feat!: completely change this behavior
```

Case 2 :
```
feat(versioning)!: completely change this behavior
```

Case 3 :
```
feat!: update the parser for commits

BREAKING CHANGE: completely change this behavior
```

The exclamation point is optional, and if used, is just before the colon.

If there is an exclamation point, the `BREAKING CHANGE` section is optional, and the commit message will be used as breaking change description.

**Comment by fattybenji** [comment]
Additionaly, since this would change the regex, I'm wondering if the first `?:` at the beginning of the "scope" line is necessary, since the colon is always supposed to be after the scope.

**Comment by relekang** [comment]
This would be nice 👍 

The `?:` at the beginning of the scope line is to make sure it is not selected as a group with the parenthesis.

**Comment by fattybenji** [comment]
I'm not 100% sure about this, but testing a bit on regex 101, it looks like the colon is selected differently, but since we have clear named groups and we don't use anything but those named groups, it looks OK.

I've just tested quickly, it looks like no tests break. Do you have awareness of a case in which it would break ? I've only tested basic commit messages with the folloxing regexes :

```
(?P<type>fix|feat|chore)(?:\((?P<scope>[^\n]+)\))?: (?P<subject>[^\n]+)(:?\n\n(?P<text>.+))?
(?P<type>fix|feat|chore)(\((?P<scope>[^\n]+)\))?: (?P<subject>[^\n]+)(:?\n\n(?P<text>.+))?
```

With 

```
chore(potato): doing some stuff
chore: doing some potato stuff
```

**Comment by relekang** [comment]
I think that should be fine

**Comment by fattybenji** [comment]
NVM, I just didn't understand "non capturing groups" well. It can be removed, but keeping it in is maybe clearer since we have capturing and non-capturing.

**Comment by relekang** [comment]
Yes, I don't think it matter much if they are there or not since we use named groups.
