### ISSUE TITLE
Clarify relation to Node's semantic-release

### ISSUE THREAD

**Issue by jezdez** [relekang/python-semantic-release#16]
There is https://github.com/semantic-release/semantic-release (a great into talk here: https://www.youtube.com/watch?v=tc2UgG5L7WM) which goes a but further than just to manually being able to bump version and push a release. E.g. It integrates with the commit message format to figure out which type of bump it is.

Could you please clarify what the differences to that package are (other than JS vs. Python)?

**Comment by relekang** [comment]
The inspiration to build this comes from the semantic-release project when I first saw it a while back. I really liked the idea and wanted something similar for Python. I think the general idea is the same: Make releases automatic and release as fast as possible after new stuff is merged. Furthermore, at the same time make the release process easier for those who would like to release manually.

At this moment this project also supports detecting bump level from commit messages, but in a simpler way than the node project. It looks for ["tags"(substrings)][tags] in commit messages and takes the highest of major, minor and patch that it finds. There is no changelog generation now, but it is feature that I would like to add in the future.

Another difference is that this project has support for forcing releases of certain types. The only reason is to make it easier for projects to start using it by forcing a release to stop the package from evaluating the whole commit log.

Please ask more if this does not answer your question :) I will watch the talk and update this thread if I find more to comment on.

[tags]: https://github.com/relekang/python-semantic-release#tags

**Comment by relekang** [comment]
To update on this, I have been talking to @boennemann about it and this project will going forward _try_ to be as similar to the node project as possible while being for python/pypi. At least it is the plan to comply with the guidelines of semantic-release.

I am closing this now, if you have more questions about this. Please ask and reopen :)
