### ISSUE TITLE
Allow for attaching of assets to releases

### ISSUE THREAD

**Issue by alandtse** [relekang/python-semantic-release#161]
Since publishing will create a release with the changelog, it'd be nice to also add an option to [add an asset to the release](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) too.

**Comment by AlphaMycelium** [comment]
What assets are you wanting to upload?

**Comment by alandtse** [comment]
Depends on the project but it would be zip files, binaries, or other non-source code assets.

**Comment by AlphaMycelium** [comment]
I've got uploads of the `dist/` folder working in #177, do you need to be able to upload things from a command-line argument or will that suffice?

**Comment by alandtse** [comment]
@AlphaMycelium Sorry for the delay in my response. I'm not using pypi but I do need to zip up a subdirectory and attach that as a release. The issue I'm running into is that because semantic release bumps the version number, I have to zip after the version is bumped. I guess I could:

1. Run `semantic-release version`
2. Zip up and store in /dist
3. Run `semantic-release publish`

But is that the best option here?

**Comment by AlphaMycelium** [comment]
@alandtse That would work.

However, if you have a `setup.py` (even if you aren't using PyPI), it is possible to [add a custom command](https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/) to automate the creation of the zip, and then use the `build_commands` option I added in #185 to run it automatically before publishing.
