### ISSUE TITLE
Bump versions in multiple files?

### ISSUE THREAD

**Issue by ttimbers** [relekang/python-semantic-release#175]
It would be nice to bump versions in multiple files. For example, in a package that uses `pyproject.toml` (and thus has the version stored there) and that also has the version stored in `package/__init__.py`. Maybe this could work by setting multiple filenames in `version_variable`?

**Comment by relekang** [comment]
> Maybe this could work by setting multiple filenames in version_variable?

Good idea, maybe just comma separate it?

**Comment by ttimbers** [comment]
Are you suggesting I should just try it and see if it works, or is that an implementation suggestion?

**Comment by relekang** [comment]
It is an implementation suggestion.

**Comment by alandtse** [comment]
As a note, I believe with Python 3.x[ libraries can source the version info from pyproject.toml](https://github.com/python-poetry/poetry/issues/273#issuecomment-570999678) so you actually don't need this feature.
