### ISSUE TITLE
Publish to conda-forge

### ISSUE THREAD

**Issue by KingDarBoja** [relekang/python-semantic-release#176]
In order to be installed on conda environments without relying on pip, I can submit a recipe at [conda-forge](https://github.com/conda-forge) so this package can be installed using `conda install -c conda-forge python-semantic-release`.

If you okay with this @relekang, I can proceed and if everything goes well, add you as maintainer 😄

**Comment by KingDarBoja** [comment]
Being tracked at [conda-forge](https://github.com/conda-forge/staged-recipes/pull/10958).

**Comment by alexifm** [comment]
Need any help with this?  I'm also interested in getting it up onto conda-forge.

**Comment by KingDarBoja** [comment]
Hi @alexifm 

I just noticed @AlphaMycelium already made the changes on the required dependencies so I can know complete the conda-forge recipe pull request 🚀

**Comment by KingDarBoja** [comment]
@AlphaMycelium the conda forge recipe PR got merged, now the generated feedstock is available at conda and the repo link: [python-semantic-release-feedstock](https://github.com/conda-forge/python-semantic-release-feedstock)
