### ISSUE TITLE
Support dots in owner names for gitlab repositories

### ISSUE THREAD

**Issue by mherzkamp** [relekang/python-semantic-release#179]
usernames and group names in gitlab repositories can contain a dot, e.g. my username in the local gitlab installation at work is of the form `firstname.lastname`. This means that there are dots in the repository url, which is parsed by `semantic_release.vcs_helpers.get_repository_owner_and_name`. However, the regex in that function does not match names with dots, presumably, in order to exclude the host part of the url. This leads to `owner` and `name` returned by this function to be `None`, and subsequent calls using these values fail.

In order to fix this, the regex has to be modified to accept dotted names as well. The host part of the url could be filtered out by matching the domain. A possible solution could look like this:

```
host = get_domain()
parts = re.search(r'{host}/([^:]+)/([^/]*?)(.git)?$'.format(host=host), url)
```

**Comment by fattybenji** [comment]
I have a suggestion for this fix, submitting PR now.

@mherzkamp can you tell me if the test cases are in accordance with your situation ?

**Comment by mherzkamp** [comment]
@fattybenji Yes, our links look like the ones in the test cases. Many thanks! :+1:
