### ISSUE TITLE
Changelog is incomplete

### ISSUE THREAD

**Issue by nicholasamorim** [relekang/python-semantic-release#193]
Hi, thanks for this project, in first place.

I want to start using this project but I'm having difficulties in generating a proper changelog.

We _just started_ using commitizen. So there's thousands of commits before the ones using commitizen. We have about 12 commits using commitizen. We have `build`, `fix`, `revert`, `feat`, `fix`, `refactor` and `improvement.

Perhaps I'm misunderstanding how to use it, but the changelog has old commits. I'm guessing it's because they just so happen to be matched by the parsing. This is fine, I reckon.

But the changelog does not contain all of the recent commits already made using commitizen, only `fix` appear in the changelog. 

Using the DEBUG env var shows things like:

```
semantic_release:history:logs 'ignored commit' UnknownCommitMessageStyleError('Unable to parse the given commit message: revert(automation): remove outdated playbook\n') +1.1ms
```

```
semantic_release:history:logs 'ignored commit' UnknownCommitMessageStyleError('Unable to parse the given commit message: improvement(apiserver): pATCH on accounts now allow for updating protecte\n\nWhen instagram accounts are authenticated as Business accounts, their IDs change. This change allows\nsm_account_id changes for instagram accounts.\n\nre #5230\n') +1.9ms
```

Others are successful on the parsing:

```
semantic_release:history:parser_angular "parse_commit_message -> (0, refactor, apiserver,connector,sorter, ('simplify logic on detecting business instagram accounts', 'As Basic Display API is not supported, the need for detecting what kind of API the account should use has been simplified. ', ''))" +259.0us
```

_But they still don't show in the changelog_.

For test, I used it for the first time - bumping version, etc. Then made a few test commits and did the same. Not all commits show.

My setup.cfg is barebones:

```
[semantic_release]
version_variable = src/sm2/__init__.py:__version__
branch = develop  # testing
```

**Comment by AlphaMycelium** [comment]
The generated changelog should only show commits created since the last release. Is that what's happening?

**Comment by nicholasamorim** [comment]
Yes and no.

It does show _some_ commits. Not all of them. Some fail on parsing, others parse successfully but don't show in the commit.

As I use `commitizen` I was expecting it to "just work". Am I missing something?

**Comment by AlphaMycelium** [comment]
Is there a pattern in the commits that parse successfully but don't show? Some categories, such as `ci` and `chore`, aren't supposed to appear in the changelog.

**Comment by nicholasamorim** [comment]
I've posted some details in the original post above - the debug logs.

**Comment by AlphaMycelium** [comment]
Looking at the debug logs you posted, `revert` and `improvement` are invalid types which is why they fail to parse. these are the types which should be parsed successfully:

https://github.com/relekang/python-semantic-release/blob/c22f69f62a215ff65e1ab6dcaa8e7e9662692e64/semantic_release/history/parser_angular.py#L13-L24

And these are the types that should show up in the changelog:

https://github.com/relekang/python-semantic-release/blob/c22f69f62a215ff65e1ab6dcaa8e7e9662692e64/semantic_release/history/logs.py#L20-L26

**Comment by relekang** [comment]
`revert` is part of [the convential commitspec](https://www.conventionalcommits.org/en/v1.0.0/) so let's add it. I guess we should look into the tags from commitizen and add them?

**Comment by AlphaMycelium** [comment]
For reference, these are the options shown by Commitizen with the default configuration.

```
 » fix: A bug fix. Correlates with PATCH in SemVer
   feat: A new feature. Correlates with MINOR in SemVer
   docs: Documentation only changes
   style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
   refactor: A code change that neither fixes a bug nor adds a feature
   perf: A code change that improves performance
   test: Adding missing or correcting existing tests
   build: Changes that affect the build system or external dependencies (example scopes: pip, docker, npm)
   ci: Changes to our CI configuration files and scripts (example scopes: GitLabCI)
```

They are all already supported by the parser.

**Comment by nicholasamorim** [comment]
Ok, so I'm at loss on why this parsed successfully yet it doesn't show on the changelog.

```
semantic_release:history:parser_angular "parse_commit_message -> (0, refactor, apiserver,connector,sorter, ('simplify logic on detecting business instagram accounts', 'As Basic Display API is not supported, the need for detecting what kind of API the account should use has been simplified. ', ''))" +259.0us
```

I'm going to create an empty public repo and try to reproduce it in a way that everyone can clone the repo and try it.

**Comment by relekang** [comment]
1. If you create a version manually with the correct version commit then everything before that will be ignored.
2. Not with the current version, but that seems like a good thing to have configurable.

**Comment by nicholasamorim** [comment]
I've created the PR #207 - which is merged but I just noticed something.

@AlphaMycelium when you improved the docs, you added:

```
The available options are:

* ``feature``
* ``fix``
* ``documentation``
* ``refactor``
* ``performance``
* ``breaking``
```

Why only these? One the main factors on why I added these is because `improvement` is missing. I also want to add `build` type, so I was expecting this to be able to be freely defined.

`improvement` and `build` are types offered by commitizen by default.

We know `build` is the code already in `parser_angular.py` - so I reckon you just forgot to add in the docs?

```
TYPES = { 
     'feat': 'feature', 
     'fix': 'fix', 
     'test': 'test', 
     'docs': 'documentation', 
     'style': 'style', 
     'refactor': 'refactor', 
     'build': 'build', 
     'ci': 'ci', 
     'perf': 'performance', 
     'chore': 'chore', 
 }
```

While improvement is not part of the official standard, this is written [here](https://www.conventionalcommits.org/en/v1.0.0-beta.4/):

> We also recommend **improvement** for commits that improve a current implementation without adding a new feature or fixing a bug.

Is there any way I can add `improvement`? If not, would a PR allowing for extra types be welcome?

**Comment by AlphaMycelium** [comment]
@nicholasamorim Those are the available types because of this:

https://github.com/relekang/python-semantic-release/blob/d5803d5c1668d86482a31ac0853bac7ecfdc63bc/semantic_release/history/logs.py#L89-L96

However, I don't see why it is initialised like that. It'd make more sense to just use all the available commit types based on the currently-enabled parser, which is most easily implemented by starting with an empty dictionary and adding new keys when a new type is encountered.

Additionally, I don't know why there is a hardcoded list of allowed types when we could simply parse anything out of the commit, and have config options for `minor_types` and `patch_types`.

**Comment by nicholasamorim** [comment]
Yeah, that makes sense to me. I guess we'd need @relekang input?

**Comment by relekang** [comment]
I agree 👍
