### ISSUE TITLE
Add creation of git tag

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#2]

**Comment by ryneeverett** [comment]
So `git tag`ing is never going to be something python-semantic-release will do? The js version seems to handle tagging so I'm curious why you decided not to.

**Comment by relekang** [comment]
It already supports it :smile:
I just forgot to link to the commit when I closed it. This was implemented in 5f4736f4e41bc96d36caa76ca58be0e1e7931069.

**Comment by ryneeverett** [comment]
@relekang That commit does look like it adds git tagging, but that seems contrary to the way python-semantic-release actually works. In #49 you say

> To know which commits to include it uses the git log since the tag of the latest release.

And indeed that seems to be how it works: python-semantic-release looks for a git tag called v{version} and if it doesn't find it git-python raises an exception.

**Comment by relekang** [comment]
The tag I mentioned in #49 is not the same tag as the 5f4736f commit introduced. How it works is that the git log evaluates the git log since the last release. Then the result of that will bump the version number based on the git log then commit it and tag it with the new version number. Lastly, it will push the commit and tag before uploading to pypi and posting changelog to Github releases.

> and if it doesn't find it git-python raises an exception.

Yeah, thats a problem. I haven't thought about how it would affect repositories. I created #51 to look into this.
