### ISSUE TITLE
Is there support for Jenkins and Gerrit?

### ISSUE THREAD

**Issue by bouncingjack** [relekang/python-semantic-release#205]
According to the documentation only `GitHub` and `GitLab` are supported.
Is a local instance of `Gerrit` supported? couldn't find a mention of it.

Is there in integration with `Jenkins`?

If not, is it possible to interact with python-semantic-release from command line?

**Comment by AlphaMycelium** [comment]
As far as I know we don't support either of these, however if you need this functionality feel free to [open a feature request](https://github.com/relekang/python-semantic-release/issues/new?labels=feature&template=feature_request.md) for each.

For interacting from the command line, take a look at [this page](https://python-semantic-release.readthedocs.io/en/latest/commands.html).
