### ISSUE TITLE
Support authenticating to PyPI with an API token

### ISSUE THREAD

**Issue by AlphaMycelium** [relekang/python-semantic-release#213]
## Description

Support PyPI authentication using an API token.

## Use cases

- Password is not stored on CI servers
- Scope can be limited to only access the project being uploaded

## Implementation

Set `__token__` as the username and send the token as the password, as described [here](https://pypi.org/help/#apitoken).

This is already possible using the current system, but it would be nicer to be able to just set the token in an environment variable such as `PYPI_TOKEN`, and have the username filled in automatically.

**Comment by BjoernLudwigPTB** [comment]
If this was implemented obviously it should be documented straightaway in the [CI example setups](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/index.html#guides) as well, besides [mentioning it in the docs](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/index.html#configuring-pypi-upload). I hope it is not too obvious to be mentioned.

**Comment by BjoernLudwigPTB** [comment]
Thanks for the quick action on that!
