### ISSUE TITLE
Workflow configurations

### ISSUE THREAD

**Issue by codegabru** [relekang/python-semantic-release#217]
## Description

Are there any plans of having [workflow configuration](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration) like in [semantic-release](https://github.com/semantic-release/semantic-release) for JS?

**Comment by AlphaMycelium** [comment]
This was not planned before, however it is a nice suggestion and I see no reason not to include it.

**Comment by codegabru** [comment]
I have been using the JS semantic-release with their @semantic-release/exec package for more than a month now. It allows you to execute scripts on certain events which is perfect to use it with any language. I don't think bringing workflows configs to the Python version will have any benefits over using the JS version with plugins so I'm closing this.

**Comment by esatterwhite** [comment]
II would generally rather not force a node.js dependency on a python project. I think this is still valid
