### ISSUE TITLE
Include the commit range since the last release into changelog

### ISSUE THREAD

**Issue by BjoernLudwigPTB** [relekang/python-semantic-release#218]
## Description

We could add a section at the bottom of the changelog that links to the commit range on GitHub for a certain release since the previous release with heading like "Latest changes".

I got the idea from [another project](https://github.com/klaussinani/ao/releases/tag/v6.9.0) and find it very useful.

Maybe we would want to introduce a new cli parameter `--include-commit-range` for that to be an optional behaviour.

## Use cases

Including the commit range would allow developers to quickly get hands on the associated commits for a certain release.

## Possible implementation

The GitHub link we get almost as a side effect since it is of the form.

```
https://github.com/<user_or_oranization>/<project>/compare/<previous-version-tag>...<current-version-tag>
```

This we could easily include in the generated changelog.

**Comment by AlphaMycelium** [comment]
Sounds good, although I think an option in the config file would be better than a cli parameter.
