### ISSUE TITLE
Why do environment checks exist?

### ISSUE THREAD

**Issue by AlphaMycelium** [relekang/python-semantic-release#224]
Why does `python-semantic-release` contain [these checks](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/index.html#environment-checks) which use environment variables set by the CI to ensure we are running on the correct branch, when it would be simpler to just provide information in the docs on how to configure the CI services to only run on the chosen branch? If this is necessary, why can't we use git to get the branch instead of the environment variable?

**Comment by relekang** [comment]
CI services have evolved quite a bit since this was written. It was not that easy to configure these things.

**Comment by AlphaMycelium** [comment]
Hm. Is there any reason not to replace this with a simple check in `vcs_helpers`?

```python
def check_branch():
    target_branch = config.get("semantic_release", "branch")
    if repo.active_branch.name != target_branch:
        raise GitError(f'Not on the configured release branch ({target_branch})')
```

**Comment by relekang** [comment]
`repo.active_branch.name` will some of the ci services be wrong because some implement shallow checkout as git init and git checkout of the ref of the commit.

**Comment by relekang** [comment]
We could always put this burden on the user to configure checkout for release in the CI services. The initial idea was to make it easier for beginners to use the tool.

**Comment by AlphaMycelium** [comment]
I think that would be a good idea, as long as we added more guides and/or example configurations for the various CI services before removing it. The checkout step shouldn't be part of Python Semantic Release since that is the job of the CI service itself to implement.

**Comment by relekang** [comment]
I am not sure we can do that. There is a lot of pipelines that do `pip install python-semantic-release` without any version number. Breaking the release in those cases would not be so bad, but starting to release from branches could have might be bad. 🤔

**Comment by AlphaMycelium** [comment]
Ah, I agree that would be a problem.
