### ISSUE TITLE
Bump TOML dependency

### ISSUE THREAD

**Issue by danth** [relekang/python-semantic-release#241]
Would be good to bump `toml` so it doesn't rely on a tight pin, as suggested by @KingDarBoja in [#176](https://github.com/relekang/python-semantic-release/issues/176#issuecomment-629879174).

**Comment by hawkaa** [comment]
Hi. I was about to open this issue myself :) I don't mind having a `__version__` parameter in my package, which is probably good practice, but it would be nice if it could update the `pyproject.toml` as well. I currently run the `version` command, change the version manually and ammend the commit.

Either way, thanks for a great project, @relekang 👍

**Comment by relekang** [comment]
Thanks @hawkaa, I opened another issue to track support for pyproject.toml as version source.

**Comment by BjoernLudwigPTB** [comment]
The `toml==0.10.0` pin results in a [conflict with the newest release of Black](https://github.com/psf/black/blob/811decd7f10fb2fb3ae343b9d9d0a3ae53b86a53/setup.py#L73).

**Comment by MicaelJarniac** [comment]
TOML seems to "loosely follow [semantic versioning](https://semver.org)", and given that it's still at major version 0:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

https://github.com/uiri/toml/blob/f8d3819d30d64b06edf38be015626ee0881e577a/RELEASE.rst

So having a strict version requirement, at least while TOML is still at major version 0, might be valid, I think.

That doesn't mean it can't be updated, just that it might be worth manually verifying compatibility before bumping the version.

But I'm pretty new to this stuff, so what I said might actually make no sense at all.
