### ISSUE TITLE
Support for mercurial 

### ISSUE THREAD

**Issue by arthurzenika** [relekang/python-semantic-release#243]
## Description

`python-semantic-release` looks great. We'd love to be able to use in on some of project which use mercurial https://www.mercurial-scm.org/

## Use cases

Diversity is important to us and I think a number of great projects hosted in mercurial could benefit from automation in the release cycle

## Possible implementation

Some work probably needs to be done in `semantic_release/vcs_helpers.py` 

On a mercurial project I get to the following error :: 

```
semantic-release changelog -D version_variable='project/__init__.py:__version__'
error: Reference at 'refs/heads/master' does not exist
```

**Comment by arthurlogilab** [comment]
Also (without an empty .git repo in there) I get : 

```sh

release changelog -D version_variable='project/__init__.py:__version__'
error: Not in a valid git repository
```

**Comment by relekang** [comment]
Happy to accept PRs for this, but I don't think it will happen unless someone with mercurial experience helps out.

**Comment by arthurlogilab** [comment]
@relekang glad to hear you are open to modifications that go towards this goal! we'll look into it (or hint at some mercurial devs/community/contributors)
