### ISSUE TITLE
Support version number from pyproject.toml

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#245]
As mentioned in both #175 and #241 it would be nice to use version number from pyproject.toml.

Let's add `pyproject.toml` as an option to `version_source`.

**Comment by Jophish** [comment]
Should the behavior of `version_source = pyproject.toml` essentially be the following?

* Get current version from `pyproject.toml` and update it
* Update all versions in other files as specified by `version_variable` or `version_pattern`
* Commit all updated files to Git (as with `version_source = commit`)

I've found that this behavior is currently possible (at least when the _only_ version we need to check/update is in `pyproject.toml`) by adding the following section to the `pyproject.toml`, using the default `version_source = commit`:

```
[tool.semantic_release]
version_variable = 'pyproject.toml:version'
```

Not sure if `version_variable` is meant to be used on non-`.py` files, but figured it was worth mentioning that there's currently a workaround to this issue, as I understand it.
