### ISSUE TITLE
Need Getting Started documentation

### ISSUE THREAD

**Issue by drmikecrowe** [relekang/python-semantic-release#255]
The current documentation is written in a way that probably seems logical to users familiar with the project.  However, for new users, a Getting Started section would be most helpful.

For example, I have my `setup.cfg` configured, my `__init__.py` has the semver properly.  If I run `semantic-release version --patch`, the version is updated correctly.

But, how do I trigger a version update in my manual build process? 

I tried this log message:
```
commit 40d84c691162937771793b3071f581c9fb6a1320 (HEAD -> feature/monorepo)
Author: Mike Crowe <drmikecrowe@gmail.com>
Date:   Mon Jul 27 07:07:02 2020 -0400

    :bug: Consolidating main
```
Shouldn't running `semantic-version version` work now?

Is the git log correct for the emoji parser?
Is the fact I'm on a branch an issue?
What needs to happen in git?  Do I need to be on a branch?  Need to tag anything?

This is a quasi-monorepo, where this python project is in a `device/` subdirectory (and other packages are in `/packages`).  Is the fact it's in a subdirectory an issue?

**Comment by AlphaMycelium** [comment]
### How do I trigger a version update in my manual build process?

- `semantic-release version` will bump the version number in the location(s) you set.
- `semantic-release changelog` shows the changelog, and publishes it to GitHub/GitLab unless you use `--noop`.
- `semantic-release publish` does both of the above, along with uploading artifacts to PyPI / GitHub Releases as configured.

### Is the Git log correct for the emoji parser?

Yes, assuming you're using the default list of emojis, that commit should create a patch release.

### Is the fact I'm on a branch an issue?

`semantic-release publish` checks out the (configurable) default branch. `semantic-release changelog` and `semantic-release version` should work on any branch.

### Need to tag anything?

No, Python Semantic Release creates tags automatically when the version is bumped.

### Is the fact it's in a subdirectory an issue?

No. The config file is looked for in the current directory, so you need to `cd` before running.

You may wish to keep an eye on #168 for better support for monorepos.

**Comment by AlphaMycelium** [comment]
I'll work on writing a better getting started page.

**Comment by AlphaMycelium** [comment]
I'll work on writing a getting started page.

**Comment by drmikecrowe** [comment]
Great, thanks!

I may help -- I got mine working, and I should be able to offer some suggestions or maybe even a starting point

**Comment by AlphaMycelium** [comment]
Okay, feel free to add your suggestions as comments/reviews on #256 :smiley:
