### ISSUE TITLE
Generation of changelog.md

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#27]

**Comment by skorokithakis** [comment]
I'd like this feature as well, it would be nice if PSR could generate CHANGELOG.md on its own every version. I'm quite liking this library, good job!

**Comment by jensgustafsson** [comment]
I would also like to add support to actually autogenerate the changelog.md file and I think the best option we have is to add a flag for that. What do you think?

I think this could be a good command:

```
$ # Output the changes to stdout: 
$ semantic-release changelog --format=markdown --output=stdout
$ # Output the changes to the changelog file: 
$ semantic-release changelog --format=markdown --output=file
```

**Comment by relekang** [comment]
> As a first step, I think we should make it possible to get the output from semantic-release changelog in a markdown format.

I am not sure what you mean by this. The output is currently valid markdown.

**Comment by jensgustafsson** [comment]
> > As a first step, I think we should make it possible to get the output from semantic-release changelog in a markdown format.
> 
> I am not sure what you mean by this. The output is currently valid markdown.

I realize that I was wrong about this. After some research I realize that it's github flavored markdown I'm asking for.

But what I don't understand is why there are two different "generate changelog"-functions in the package. When running `semantic-release publish` a different markdown format is used compared to the output from the command `semantic-release changelog`.

**Comment by relekang** [comment]
Good point, I don't remember why they are different. Really see no reason for the command to not just print what we send to Github.

**Comment by wyardley** [comment]
If I'm not mistaken, it _can_ currently generate the changelog now, right?
That said, it would be nice to be able to customize the format a bit.
I like the format from Node semantic-release / conventional-changelog, so I build ours this way:
`npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0`

There's no plugin arch or way to trigger a shell command on successful release with this project, right?

**Comment by browniebroke** [comment]
I use PSR as Github action, and I'm also interested in this feature. Currently, I run another action for that in the same workflow, however it means I need to either run it before or after, which are both suboptimal:

- If I run the changelog action before PSR, I don't know the new version yet.
- If I run the changelog action after PSR, the `changelog.md` included in [the versioned documentation](https://docs.readthedocs.io/en/stable/versions.html) for the release made by PSR isn't up to date

Ideally I'd like to update the changelog file *after* I knowing the new version, but *before* tagging the new release. That's my use case, wondering if others share the same? Is it the main use case?

Right now, the steps are:

1. Check if a new version is required, if not, stop here
2. Set the new version
3. Commit
4. Tag the new version
5. Push changes
6. Push tags
7. Build dists
8. Publish to PyPI
9. Create release with changelog

So we get the changelog content at step 9 but we would need to update the changelog file between steps 1 and 2. 

Also step 1, 2 and 3 are all happening in the `version()` command, I think it would make sense to break this up to achieve this.

Do people agree with the suggested approach? Is there some aspects that I'm missing?

I've started a draft PR #266 for that, but still a long way to go.

**Comment by wyardley** [comment]
@browniebroke that sums up my problem pretty well too. We ended up taking the approach where we publish off the tag that’s cut, so we don’t have the right changelog in the release.

Not a dealbreaker for our internal use, but still not ideal.
