### ISSUE TITLE
Using 'chore' in my commit message does not result in a version bump

### ISSUE THREAD

**Issue by wimnat** [relekang/python-semantic-release#271]
## The problem

I make a commit using one of the defined TYPEs e.g `chore: i did something`.
I then ran semantic-release publish --noop

My version is not bumped and I just get a warning:

```
warning: Unknown bump level 0
No release will be made.
```

If i use `feat`, `fix` or `perf` it works.  Looking at [the code](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/parser_angular.py#L38-L45) this is expected.  So, why are all the other TYPEs defined and then not included as a MINOR_TYPE or PATCH_TYPE?

## Expected behavior

I expected my version to be bumped.

Although when i look at https://github.com/relekang/python-semantic-release/blob/master/semantic_release/history/parser_angular.py it seems that only `feat`, `fix` or `perf` will actually cause a version bump.

**Comment by danth** [comment]
- `feature`, `fix`, `perf`, and `BREAKING CHANGE:` paragraphs, will bump the version and be included in the changelog
- `docs` will appear in the changelog for the next release, but does not trigger a version bump on its own
- `style`, `refactor`, `test`, `chore` have no effect (unless you add them to [`changelog-sections`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#changelog-sections))

---

In the [Angular commit style guide](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type), `chore` is described as:

> Changes to the build process or auxiliary tools and libraries such as documentation generation

This type of change shouldn't affect the released package, so we don't create an unnecessary version bump. If you'd like to always create a release, you can enable [`patch_without_tag`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#patch-without-tag).
