### ISSUE TITLE
Squash Merge Support

### ISSUE THREAD

**Issue by RyanFleck** [relekang/python-semantic-release#272]
## Description

*A clear and concise description of your idea.*

If the commit message could be parsed for multiple tags, that would be great! For instance, I squash-merged a branch with this as the commit message:

![image](https://user-images.githubusercontent.com/28709508/98408749-ec4d3780-202e-11eb-8e6e-c6febd534ccc.png)

And it would be great if all these tags/messages could be listed in the changelog.

## Use cases

*List some reasons this would be useful.*

Properly support collections of squash-merged commits.

## Possible implementation

*Describe any ideas you have for how this could work.*

Modify the commit parser and allow it to pull multiple changes from a long commit message.

Tested on repository: <https://github.com/Small-Minds/Democracy>

**Comment by wyardley** [comment]
IMO, this seems risky; while different people will have different workflows, what we usually do is either to regular merge or rebase merge directly to trunk, or, when more control is wanted over the release process, enforce linear history into a dev or staging branch (squash or rebase merge only), then make a release PR into trunk that gets merged with a merge commit and / or rebase merged. Care has to be taken to merge the release PR the right way, or automate it, but this works pretty well.

I would guess that a feature like this could lead to mistakes and / or messy changelogs / release notes. Sometimes atomic commits are useful, but that’s what tidying up / squashing commits in branches is for.

**Comment by relekang** [comment]
I agree that this is going to be tricky and have many pitsfalls without the pros outweighing this.

**Comment by RyanFleck** [comment]
...if I have time, would you be open (@relekang ) to merge a PR that adds a flag and completes this operation?
