### ISSUE TITLE
publishing without pushing dist to GH release

### ISSUE THREAD

**Issue by wyardley** [relekang/python-semantic-release#273]
I've got a project where I don't actually have any dists to build or files to publish to the GH release. I've currently got the current configuration in `setup.cfg`. After looking at the config, I tried adding `upload_release = false` (see below), which I thought would suppress the error below, but I'm still getting it.

```
[semantic_release]
branch = main
version_variable = datadog-agent/checks.d/__version__.py:__version__
build_command = true
remove_dist = false
upload_release = false
upload_to_pypi = false
commit_message = 'chore(release): release version {version} [skip ci]'
```

I'm getting a successful tag cut / changelog pushed / GH release notes published, but getting the following error:
```
Posting changelog to HVCS
Uploading to HVCS release
error: [Errno 2] No such file or directory: 'dist'
```
Any suggestions? Also, is there a simpler way to not try to build anything besides setting `build_command` to `true`?

**Comment by danth** [comment]
The option you're looking for is called [`upload_to_release`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#upload-to-release), not `upload_release`.  Disabling both upload locations should stop the build command from running.

**Comment by wyardley** [comment]
Thanks. I couldn't find it in the docs somehow, and was looking at the variable within the code.
Is it expected that semantic-release won't error on unexpected configuration options?

**Comment by relekang** [comment]
It is mentioned here https://python-semantic-release.readthedocs.io/en/latest/configuration.html#upload-to-release and yes we don't validate unknown configuration variables as it is now.
