### ISSUE TITLE
Support GitHub Enterprise

### ISSUE THREAD

**Issue by prabu28** [relekang/python-semantic-release#277]
push_new_version(, auth_token='XXXXXXX-XXXXXX-XXXXXXXXX', owner='appowner', name='MyAPI', branch='dev', domain=**'github.com'**)

is there a way to make publish work for github enterprise  ? some thing like **github.mycompany.com**
 i tried setting domain = github.mycompany.com in setup.cfg but that dint help .

**Comment by danth** [comment]
Currently, Python Semantic Release does not support this.

If the GitHub Enterprise API uses the same endpoints as `api.github.com`, only under a different domain name, we can add a configuration option to set `API_URL` in `hvcs.py`.

**Comment by prabu28** [comment]
> Currently, Python Semantic Release does not support this.
> 
> If the GitHub Enterprise API uses the same endpoints as `api.github.com`, only under a different domain name, we can add a configuration option to set `API_URL` in `hvcs.py`.

thanks for the info  @danth

**Comment by wyardley** [comment]
I was looking at implementing this, using `hvcs_domain` as an option that would work for both GHE and Gitlab, but it seems that Gitlab uses `CI_SERVER_HOST` for this already.

https://github.com/relekang/python-semantic-release/blob/af4cd6a283ac8184637c438fc11f35aed7640cee/semantic_release/hvcs.py#L270

Also, presumably it may be necessary to use the domain from hvcs.py for the links in the changelog?

I'm still thinking it's cleanest to allow `hvcs_domain` to be configurable. I have some work in progress on this, and can push it and work on tests after we see what happens with #282.

May be a more tidy / efficient way to do some of this, but this is what I have thus far.
https://github.com/relekang/python-semantic-release/compare/master...wyardley:wyardley-hvcs-domain?expand=1

**Comment by wyardley** [comment]
@prabu28: do you know if the API hostname is consistent? e.g., if you have a vanity domain of github.example.com for GHE, will you use github.example.com, or api.github.example.com for the API? It seems like some instances have the API hostname, but that maybe it should work without it, and that might be the safest / most consistent?

**Comment by prabu28** [comment]
> @prabu28: do you know if the API hostname is consistent? e.g., if you have a vanity domain of github.example.com for GHE, will you use github.example.com, or api.github.example.com for the API? It seems like some instances have the API hostname, but that maybe it should work without it, and that might be the safest / most consistent?

hi @wyardley  https://github.mycomany.com/api/v3 is our api url
