### ISSUE TITLE
Only last commit is read (partial changelog and invalid version bump)

### ISSUE THREAD

**Issue by Toilal** [relekang/python-semantic-release#301]
## The problem

On my project, release is performed considering the last commit entry only. Changelog has the last commit only (a fix), and it has been incremented as a patch version instead of a minor one (because one missing commit is a new feature). 

## Expected behavior

It should consider all commits from the previous version to generate changelog and version bump.

## Additional context

Project repo: https://github.com/gfi-centre-ouest/docker-devbox-ddb

Release is performed with github actions (https://github.com/gfi-centre-ouest/docker-devbox-ddb/runs/1591842201?check_suite_focus=true)

The way python-semantic-release retrieve the previous released version is not very clear. There's surely something wrong in my configuration, but I can't find what.

It occured everytime since I have tried to implement semantic-release.

I had to fix the changelog manually after the release, [here](https://github.com/gfi-centre-ouest/docker-devbox-ddb/commit/9507778794186ebf7864f7ebaaad6e7e9ea3ce9d) and [here](https://github.com/gfi-centre-ouest/docker-devbox-ddb/commit/3e7f9e09b9c16c1c17168187a11b70272e22c74e)

Maybe something is not well supported into my settings, https://github.com/gfi-centre-ouest/docker-devbox-ddb/blob/9507778794186ebf7864f7ebaaad6e7e9ea3ce9d/setup.cfg#L1-L7, maybe commit_subject ...

**Comment by danth** [comment]
The default branch in your repository is `develop`, but Python Semantic Release reads commits from `master` by default. Can you try adding this to your settings?

```ini
[semantic_release]
branch = develop
```

**Comment by Toilal** [comment]
I use master to release though. I manually perfom a merge of develop in master (fast-forward) when I want to release a new version, github action is triggered on master branch only.

When semantic-release publish command is invoked by github action, master and develop points to the same commit.

**Comment by Toilal** [comment]
But maybe the github action "checkout" makes the git branch detached ... I'll try to add `git checkout master` before running the semantic-release command, maybe it will solve the issue.

**Comment by danth** [comment]
`actions/checkout@v2` only fetches the most recent commit by default. The workflow step needs to be configured like this:

```yaml
- uses: actions/checkout@v2
    with:
      fetch-depth: 0
```

You may also want to read this page about [Python Semantic Release on GitHub Actions](https://python-semantic-release.readthedocs.io/en/latest/automatic-releases/github-actions.html).

**Comment by Toilal** [comment]
That's it i think, great :). It seems I read this page to fast, thanks.
