### ISSUE TITLE
Is it possible to release a fix/patch to a previous version? 

### ISSUE THREAD

**Issue by Doggie52** [relekang/python-semantic-release#305]
Let's say I've released v1.0.0 a while ago and have now released v2.0.0. I now discover that there was a bug in v1.0.0 that I'd like to release a fix for, ie v1.0.1.

Can I do that with this package and, if so, how would I go about doing that?

**Comment by relekang** [comment]
It should be possible, try something like this:

1. Create a new branch for the tag `stable/v1.x.x` or something like that.
2. Set the [branch config](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#branch) to that branch.
3. Run the release 🎉 

I'm closing the issue, but please reopen if it does not work.

**Comment by Doggie52** [comment]
Great - that's a start and indeed that works. However, now I'd like to reintroduce that commit with the fix into my next release, as the bug was technically present in both v1 and v2. Might not be one correct way to do it, but what's recommended? That I cherry-pick that commit into v2 and commit it in there too?
