### ISSUE TITLE
allow uploading to custom package index

### ISSUE THREAD

**Issue by jkuball** [relekang/python-semantic-release#310]
## Description

It is possible to set up your own custom python package index. It is sadly not possible to upload to it via python-semantic-release. Right now you have to set `upload_to_pypi = false`, `remove_dist = false` and manage the upload yourself.

## Use cases

E.g. for company-internal python packages that can't be hosted on the PyPI.

## Possible implementation

I think it needs to be possible to add package indices (identifier, index url, basic auth username/password) and a config param that is a list of identifiers, like `upload_to=pypi,custom_index_indentifier`. Its default value can be `pypi` and the pypi is configuread as an always known package index.

Twine can upload to other package indices with `--repository-url`.

**Comment by relekang** [comment]
#303 should solve this I think?

**Comment by jkuball** [comment]
Oh yeah, it surely does! Sorry, I forgot to re-check the current activity of this repo!

**Comment by lewgordon** [comment]
It'd also be nice if there was an option for the twine invocation to respect the use of `.pypirc` over the other options.

**Comment by fleXible** [comment]
@relekang This is actually solved.
