### ISSUE TITLE
Pre-releases

### ISSUE THREAD

**Issue by Golodhros** [relekang/python-semantic-release#312]
Hi there, thanks for your work on this project!

Is there a way to setup python-semantic-release to do pre-releases?

**Comment by danth** [comment]
@Golodhros There isn't currently any support for pre-releases, the main problem is how to automatically decide whether a commit should trigger a normal release or a pre-release.

**Comment by Golodhros** [comment]
I see, 
What I am trying to do is to create a pre-release with every commit, and a regular release only with tags.

**Comment by shaunc** [comment]
Another approach is use env variables & branches -- e.g. like [go-semrel-gitlab](https://juhani.gitlab.io/go-semrel-gitlab/pre-release/).
