### ISSUE TITLE
[docs] add CI and auto release example

### ISSUE THREAD

**Issue by codingjoe** [relekang/python-semantic-release#32]
It would be great if there would be an example in the documentation on how to setup the release on a ci system like, travis-ci or others.

---

Edit by @relekang:

Lets add guides for these:
- [x] Travis CI
- [ ] Circle CI
- [ ] Semaphore CI
- [ ] Snap CI

**Comment by relekang** [comment]
I finally got it working with Travis. I will be documenting it sometime as soon as possible, but the key is adding the following to .travis.yml. You will need version 3.4.0 for this to work.

```
after_success:
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- pip install python-semantic-release
- git checkout master
- semantic-release publish
```

The plan is to make python-semantic-release handle the branch change if necessary, but it does not do that yet(#39). Furthermore, there is an issue, #40, if solved will remove the need to set git user.

In addition some environment variables needs to be set `PYPI_USERNAME`, `PYPI_PASSWORD`, `GH_TOKEN`. Either use travis encrypt to add it to the travis file or add is as a secret on the settings page of the project on travis. The Github token will need the `public_repo` or `repo` scope.

**Comment by codingjoe** [comment]
@relekang thank you so much, this is great. I'd like to include it in [Django-CC](https://github.com/codingjoe/django-cc), a project me and a couple of other people are currently working on.
It would be great to add the config to the example files.

**Comment by relekang** [comment]
Cool, i added [guide for travis](http://python-semantic-release.readthedocs.org/en/latest/automatic-releases/travis.html) and [more docs about ci](http://python-semantic-release.readthedocs.org/en/latest/automatic-releases/index.html)

**Comment by codingjoe** [comment]
@relekang thank you so much. Hey, I know I'm asking a lot here, but would you be up to creating a release section [here](https://github.com/codingjoe/django-cc/blob/master/examples/.travis.yml) using the regular angular parser? That would be amazing!

BTW: Merry Christmas!

**Comment by relekang** [comment]
Yeah, sure. Probably not today though :christmas_tree: 

Happy christmas :sparkles:

**Comment by relekang** [comment]
@codingjoe Have to find a way to support multi environment builds first. This requires that one has only one environment in the build matrix. Any ideas on how to solve it?

**Comment by codingjoe** [comment]
Nope, this is an ongoing issue with travis ci. It s*cks that they don't start the deploy in a separate container after the build failed of succeeded. I really hope they are going to fix that soon.

**Comment by bradwood** [comment]
What about gitlab-ci ?

**Comment by relekang** [comment]
@bradwood Sure, prs are welcome 😃
