### ISSUE TITLE
How to force a release?

### ISSUE THREAD

**Issue by chbndrhnns** [relekang/python-semantic-release#327]
I am running your tool in a GitLab CI job and sometimes it is forgotten to use the correct commit type to trigger a release. Is there any way to run the CI job and pass in a variable that would make `python-semantic-release` create a release no matter what the commit messages say?

**Comment by danth** [comment]
You can use the command line option `--major`, `--minor` or `--patch` to force a version bump of the corresponding level. Currently these can't be passed as a variable.
