### ISSUE TITLE
Update python-gitlab dependency to 2.6.0

### ISSUE THREAD

**Issue by lyz-code** [relekang/python-semantic-release#329]
## The problem

Please consider updating python-gitlab to the latest version, 2.6.0. It will [prevent dependabot PRs](https://github.com/lyz-code/mkdocs-newsletter/pull/10) from showing up.

## Expected behavior

python-semantic-release uses the latest version of its dependencies

**Comment by blueyed** [comment]
For reference: it is currently pinned at `<2`: https://github.com/relekang/python-semantic-release/blob/20d79a51bffa26d40607c1b77d10912992279112/setup.py#L45
