### ISSUE TITLE
Poetry + PSR: Error when uploading to PyPI

### ISSUE THREAD

**Issue by browniebroke** [relekang/python-semantic-release#331]
## The problem

I'm using PSR as Github Action on one of my project and it worked great until around a week ago. The package where I'm using it is using Poetry as package manager. It wasn't a problem until recently but maybe an imcompatibility has been introduced recently.

You can see how it's configured here: https://github.com/browniebroke/django-codemod/blob/e23b8bbcb44144c8b96b2fcbee48e9ea06908316/pyproject.toml#L64-L68

```
[tool.semantic_release]
branch = "main"
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "django_codemod/__init__.py:__version__"
build_command = "pip install poetry && poetry build"
```

The release failed when trying to upload to PyPI:

```
Uploading to PyPI
debug: upload_to_pypi(, path='dist', skip_existing=False, glob_patterns=None)
Traceback (most recent call last):
  File "/usr/local/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/twine/__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "/usr/local/lib/python3.7/site-packages/twine/cli.py", line 43, in dispatch
    registered_commands = entry_points(group="twine.registered_commands")
TypeError: entry_points() got an unexpected keyword argument 'group'
error: Encountered a bad command exit code!
error: 
error: Command: 'twine upload -u \'__token__\' -p \'***\' "dist/*"'
```

Anyone else got this problem? Locally, I'm able to build my package with Poetry and upload with Twine without problem...

## Expected behavior

Release should be uploaded without error:

- https://github.com/browniebroke/django-codemod/runs/1817551664?check_suite_focus=true#step:4:230

## Additional context

See examples of failed release here: 

- https://github.com/browniebroke/django-codemod/runs/2209900440?check_suite_focus=true#step:4:180
- https://github.com/browniebroke/django-codemod/runs/2253314837?check_suite_focus=true#step:4:220

**Comment by relekang** [comment]
There is a conflict of dependencies resulting in this message after installing poetry.

> twine 3.4.1 requires importlib-metadata>=3.6, but you have importlib-metadata 1.7.0 which is incompatible.

I'll move semantic-release dependencies into a virtualenv to encapsulate it.

**Comment by browniebroke** [comment]
Thanks for the quick fix, just to confirm that it worked on my side 👍
