### ISSUE TITLE
Support http instances

### ISSUE THREAD

**Issue by rpocase** [relekang/python-semantic-release#332]
## Description

Currently, all URLs are hard coded to HTTPS. It would be nice to support HTTP instances as well.

## Use cases

This is useful in instances where you would like to test semantic-release but don't necessarily have a trusted cert for an instance (gitlab or github)

## Possible implementation

I would expect this to be detected based on local git config or something provided in the environment.

**Comment by relekang** [comment]
I don't think we will put any effort towards supporting this. The security downside of sending tokens etc over http by accidentally configuring something with http that supports https. With letsencrypt and friends it should be doable to use https.
