### ISSUE TITLE
PSR + Poetry: most of pyproject.toml deleted during release

### ISSUE THREAD

**Issue by browniebroke** [relekang/python-semantic-release#336]
## The problem

Running PSR via the Github action, on a project using Poetry, and [the release failed](https://github.com/browniebroke/netlify-builds/commit/09ec763e8576be83fe20cffb0597917b65254052) because PSR removed some fields which are required by Poetry: name and description.

Here is [the commit from PSR](https://github.com/browniebroke/netlify-builds/commit/09ec763e8576be83fe20cffb0597917b65254052), it removed most of the `pyptoject.toml` content.

## Expected behavior

Package is released without errors. It was working 27 days ago at least (last release).

## Additional context

Even more confusing, the only release of PSR we had in the meantime is 7.15.4 which seems like a pretty trivial change.

**Comment by browniebroke** [comment]
Maybe relevant, I see there was 2 version of tomlkit this month: https://pypi.org/project/tomlkit/#history

**Comment by IceTDrinker** [comment]
hi is the tomlkit issue still a thing ?

**Comment by browniebroke** [comment]
There is now a test in PSR to make sure that it works as expected. If you unpin and the problem is still present, the test suite should fail. If the test suite passes, that probably means the original issue was resolved.

**Comment by IceTDrinker** [comment]
> There is now a test in PSR to make sure that it works as expected. If you unpin and the problem is still present, the test suite should fail. If the test suite passes, that probably means the original issue was resolved.

Ok I'll check some time next week, we have some dev dependencies with tomlkit and semantic release sometimes causing head aches because of the pin in PSR
