### ISSUE TITLE
Support formatting CHANGELOG as restructured text

### ISSUE THREAD

**Issue by rbpatt2019** [relekang/python-semantic-release#351]
## Description

As the name says. It would be brilliant to be able to choose to format the CHANGELOG as an `rst` file rather than a `md` file.

## Use cases

In my case - building documentation with Sphinx. Currently, I work around this by linking out to the release history on github, which works but always feels less than ideal.

## Possible implementation

To be frank, I'm not sure how much effort this would take to add/maintain. If there is interest from the project maintainers, I'll tackle myself and open a PR.

Thanks for the excellent tool!

**Comment by danth** [comment]
This will require writing restructured text versions of the 3 components:

https://github.com/relekang/python-semantic-release/blob/e9d2916094dd6a537adc6c643d759c3f49100941/semantic_release/changelog/changelog.py#L52-L66
https://github.com/relekang/python-semantic-release/blob/e9d2916094dd6a537adc6c643d759c3f49100941/semantic_release/changelog/changelog.py#L69-L84
https://github.com/relekang/python-semantic-release/blob/e9d2916094dd6a537adc6c643d759c3f49100941/semantic_release/changelog/compare.py#L21-L26

Then, switch between markdown / restructured text using a new option.

Perhaps make the [`changelog_components`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#changelog-components) option accept classes which support both formats - for backwards compatibility we'd assume that functions return the currently selected format.

**Comment by rbpatt2019** [comment]
Sorry for the lag, I was away on holiday! 
Recently discovered the MyST plugin for using Markdown with Shinx. The plugin is dead easy, and completely eliminates the need for a rst CHANGELOG. Happy to consider this closed!
