### ISSUE TITLE
Support projects *only* using tags for version tracking

### ISSUE THREAD

**Issue by jacobolofsson** [relekang/python-semantic-release#354]
## Description

I would like to use semantic-release to publish new version tags in git, without updating any files/creating additional commits.

## Use cases

I am working on a project which uses setuptools_scm to generate version numbers based on git tags (`__version__.py` is not checked in, but generated at build time). I would like to use semantic-release to automatically create a new version tag and publish it (no need to create a new commit). With the current settings I have not found a way to do this, since at least 1 file is required to be updated with a new version number
```
error: must specify either 'version_variable', 'version_pattern' or 'version_toml'
```

## Possible implementation

Add a new option along the lines of: `tag_only` or `no_commit` or etc, which would cause the tool to only create a new vcs tag, do not try to match version_* options to any file, and do not create a changelog.

Another idea would be to not enforce 'version_variable', 'version_pattern' or 'version_toml', but only add a tag if none of them is present.

**Comment by danth** [comment]
Have you tried changing the [`version_source`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-source) option to `tag`?

**Comment by jacobolofsson** [comment]
> Have you tried changing the [`version_source`](https://python-semantic-release.readthedocs.io/en/latest/configuration.html#version-source) option to `tag`?

Yes, I did. I looked a little bit more into it, and the problem is that bump_version() will always call set_new_version() which will always call load_version_declarations() which then raises ImproperConfigurationError if all three options:  'version_variable', 'version_pattern' or 'version_toml' are empty.
https://github.com/relekang/python-semantic-release/blob/2111d1e81d3f6210ad00289a788ede199a17ee33/semantic_release/history/__init__.py#L312

Disclaimer: As far as I can tell at least

**Comment by jacobolofsson** [comment]
I guess this could be fixed by simply changing line 312 to:
```python
if not declarations and config.get("version_source") == "commit":
```
(just need to make sure the changelog is also properly considered)

**Comment by jacobolofsson** [comment]
If anyone else is interested, my workaround was to assign a random file to `version_pattern` in my pyproject.toml:
```
version_pattern = "README.rst:foo"
```
The file needs to exist, but the pattern does not have to match anything

**Comment by danth** [comment]
> how do I get started? I read contributions guide so presumably fork -> fix + tests -> PR..?

@rafcio19 Yes, just fork, commit your changes to a new branch, and then create a pull request. Make sure to follow the [Angular commit style](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commits) in all of your commit messages.
