### ISSUE TITLE
Option for the GitHub Action to open a PR instead of directly pushing the changes

### ISSUE THREAD

**Issue by MicaelJarniac** [relekang/python-semantic-release#355]
## Description

An option for the GitHub Action to open a pull request instead of directly pushing the changes to the branch.

## Use cases

If a repository uses branch protection rules, the Action might be unable to directly push to the target branch, and in this case, a pull request would likely be a valid alternative.

https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/42

## Possible implementation

For this example, let's consider that the default branch is `main`, and it has branch protection rules that require changes to be submitted through pull requests and such pull requests to have approving reviews.

1. User submits a PR to `main` with proposed changes
2. PR gets approved, changes merged to `main`
3. GitHub Action gets triggered to do a release
4. Action creates a new branch, named after the new version, and makes the necessary changes there (updating changelog file, bumping version variable, etc)
5. Action opens a PR to merge this newly created branch to `main`
6. User with necessary rights accepts and merges this PR
7. GitHub Action gets triggered to do a release
8. This time, the Action would detect this PR is actually the result of a previous Action run, and so instead of creating a new PR, it actually does the releases to PyPI and GitHub Releases

**Comment by MicaelJarniac** [comment]
By the way, I do realize how unusual this is, and it's probably not a very good idea.

**Comment by relekang** [comment]
I think a way to solve this outside of the psr action if you want is to:

* After merge make action workflow create new branch
* Run semantic-release action
* Add creation of the PR in a separate step in the worklow

**Comment by MicaelJarniac** [comment]
Seems like a good idea, and less hacky than the "solution" I proposed.

**Comment by relekang** [comment]
Closing this, please re-open if it does not work out.

**Comment by jenstroeger** [comment]
I ran into the following problem: the `main` branch has the _Require pull request reviews before merging_ protection rule enabled which requires two or more approvals. The result is that the Github Action can’t push directly to `main` and update the release.

So the proposal to generate a PR instead of pushing directly would help.

**Comment by relekang** [comment]
@jenstroeger have you tried this https://github.com/relekang/python-semantic-release/issues/355#issuecomment-881496754?

**Comment by jenstroeger** [comment]
@relekang I don’t quite follow the suggestion in that comment, would you mind elaborating? Thanks!

**Comment by relekang** [comment]
Something along the lines of

```
branch="release-$(git rev-parse --short HEAD)"
git checkout -b $branch
semantic-release --define "branch=$branch" publish
gh pr create --title Release --body "Automatic release" --head $branch
```

I don't have the time now to explain a lot, but if you have specific questions please ask.

**Comment by MicaelJarniac** [comment]
How is this going to work in the upcoming version?
- #487
