### ISSUE TITLE
Semantic-release  doesn't work when git and python packages are installed into user-space

### ISSUE THREAD

**Issue by laercio-barbosa** [relekang/python-semantic-release#356]
## The problem
semantic-release doesn't work when git and python packages are installed into user-space in Windows 10.

*A clear and concise description of what the bug is.*
When Python is installed into "c:\program files" and packages  are installed into user-space or if git is installed into user-space, semantic-release doesn't work due to these paths are not set under PATH environmental variable.

user-space --> somewhere into "c:\users\username\AppData\..."

## Expected behavior
command "semantic-release --help" should show information after installation

*A short description of what you expected to happen.*
After installation semantic-release should execute its commands.

## Additional context
- Windows 10
- Python 3.9.6 installed into c:\program files\
- Git installed into user-space (c:\users\username\AppData)
- Install semantic-release without administrative privileges
- Company policy only allows installations after privileges elevation

*Add any other information that could be useful, such as your configuration file or an example commit.*
By installing Git under "c:\program files" and installing semantic-release with administrative privileges it works.

**Comment by danth** [comment]
Is it possible to add the userspace directory to $PATH?

**Comment by laercio-barbosa** [comment]
Hi

I think so. But it will be 2 large strings into $PATH (as they are totally different folders). The side effect could be those $PATH already full. But I will test to add only the "c:\users\username\" into $PATH .


Anyway, if it is possible a suggestion, what do you think to make semantic-release look into these folders by itself?

I will let you know after my tests here.

**Comment by laercio-barbosa** [comment]
Hi

I figured out Git installation path is not a problem. Only semantic-release script path is. So, if I add

_c:\users\user_name\appdata\roaming\python\python39\scripts\_

to the PATH, it works fine. Any sub string of this path don't work (for obvious reasons).
I think we can close this issue. I would suggest to propose label it as feature, making semantic-release also look into full path if nothing is found in common Python folder. But, I think this is a problem from Windows as it doesn't locate the executable file if PATH doesn't point to the right folder.

So, lets close it!
