### ISSUE TITLE
Version increment can be None for non-empty commits

### ISSUE THREAD

**Issue by okainov** [relekang/python-semantic-release#367]
## The problem

Having commit history like:
```
* 3c16972 2021-08-04 (HEAD -> test, origin/test) random: fix API account
* e51d98c 2021-07-27 (tag: v0.1.0, origin/master) ci: add initial CI (#1)
* f1ab729 2021-07-27 (master) chore: add logs
```

The last commit is made in accordance with https://conventionalcommits.org/, but "type" is something not standard ("random" in this case). 

I do expect that such commits should lead to patch-version increment (from `1.2.3` to `1.2.4`). However currently it leads to "None" increment...
```
    current_version = history.get_current_version_by_tag()
    level_bump = history.logs.evaluate_version_bump(current_version, None)
```

## Expected behavior

There should be non-trivial inrement.

## Additional context

*Add any other information that could be useful, such as your configuration file or an example commit.*

**Comment by relekang** [comment]
Would be okay to add this as an option set to false in an minor change and then do a major release to set the default to true.

**Comment by relekang** [comment]
This is configurable through
```
parser_angular_default_level_bump=patch
```
