### ISSUE TITLE
Add a Scipy/Numpy commit message parser

### ISSUE THREAD

**Issue by FirefoxMetzger** [relekang/python-semantic-release#368]
## Description

I am quite excited about the idea behind this repository, and I'd love to give it a try. However, my repo follows more of a numpy/scipy style for commit messages. Both are - essentially - the same style.

[Numpy format](https://numpy.org/doc/1.13/dev/gitwash/development_workflow.html#writing-the-commit-message)
[Scipy format](https://docs.scipy.org/doc/scipy/reference/dev/contributor/development_workflow.html#writing-the-commit-message)

What I'd like to have/contribute is a parser for this particular style of commit message. When I looked at the existing angular parser, it seemed straightforward enough to write, so I will give it a shot either way, but I was wondering if there is interest (and support) here for me to contribute it back upstream.

## Use cases

Adding semantic release to any python repo that follows the numpy/scipy commit message format. 

I will adopt it [here](https://github.com/FirefoxMetzger/ropy) and - assuming semantic release proves worthwhile - [imageio](https://github.com/imageio/imageio) (which I help maintain) might adopt it, too.

## Possible implementation

TBD

**Comment by danth** [comment]
A pull request adding this would be welcome! There is a section in the docs about [writing your own parser](https://python-semantic-release.readthedocs.io/en/latest/commit-log-parsing.html#writing-your-own-parser).
