### ISSUE TITLE
version files only

### ISSUE THREAD

**Issue by falcorocks** [relekang/python-semantic-release#375]
HI @relekang ,
thank you so much for this great project!
I'd like to suggest a change, and even implement it in a PR but first I'd like to check with you on how to do it and how would you feel about it.

We want to use your cli to bump versions, without any git interaction.
Currently calling `semantic-release version` from the cli ends up here:

```def bump_version(new_version, level_bump):
    """
    Set the version to the given `new_version`.
    Edit in the source code, commit and create a git tag.
    """
    set_new_version(new_version)
    if config.get(
        "commit_version_number",
        config.get("version_source") == "commit",
    ):
        commit_new_version(new_version)
    if config.get("version_source") == "tag" or config.get("tag_commit"):
        tag_new_version(new_version)

    logger.info(f"Bumping with a {level_bump} version to {new_version}")
```

Of all this, we really just want to run `set_new_version(new_version)`.
Now we have to manually delete the tag and the commit, which is error prone and clunky.
I would like to propose to only be able to change the version from the CLI.

----

I can think of several ways to implement this:

* new cli command that just calls `set_new_version(new_version)`
* flag in `bump_version(..) to disable the steps after `set_new_version(new_version)`

The only critical thing for us is that we can do this from CLI in our CI system.
What do you think?

Thanks!

**Comment by relekang** [comment]
Do you commit it manually? I am asking because the automatic versioning is based on either the commits/tags.
