### ISSUE TITLE
Regular expression support for non `SemVer` string

### ISSUE THREAD

**Issue by josuemtzmo** [relekang/python-semantic-release#379]
## Description

Use `version_pattern` and a regular expression to support non `SemVer` string. 

## Use cases

I've created an add-on for Blender (3D visualization software) and I would like to automatically bump the version of the add-on. Although I personaly use `SemVer` conventions, Blender does not use this convention and it requires a dictionary containing the key {"version": (major, minor, patch)}. Thus, It will be great to do something like:

version_pattern = [
    'blendernc/__init__.py:"version": \((\d+\, \d+\, \d+)',
]

This will be really useful for add-ons of any kind where the parent software uses a different convention other than `SemVer`. 

## Possible implementation

See above, the idea will be to be able support an __init__.py file containing: 

```
#!/usr/bin/env python3
import bpy

bl_info = {
    "name": "BlenderNC",
    "author": "Oriol Tintó Prims & Josué Martínez-Moreno",
    "description": "Blender Add-On to visualize geo-scientific data",
    "blender": (2, 83, 0),
    "version": (0, 4, 39),
    "location": "View3D",
    "warning": "Early version",
    "category": "Generic",
    "License": "MIT",
}
```

and by using `poetry` do:

```
[tool.semantic_release]
version_pattern = [
    'blendernc/__init__.py:"version": \((\d+\, \d+\, \d+)',
]
```
to automatically update the version. Currently, the printed error is:
```
$ semantic-release version
Creating new version
Current version: 0, 4, 39
error: 0, 4, 39 is not valid SemVer string
```

**Comment by relekang** [comment]
I don't think that is worth the effort. It can be solved in the package by having a variable on the format `"x.y.z"` and parse it:

```
version = "1.0.0"

bl_info = {
    ...
    "version": tuple([int(n) for n in version.split('.')]),
}
```

**Comment by josuemtzmo** [comment]
I wish it was as simple as to parse using a tuple comprehension. I've already tried that and then I realized that Blender reads the `bl_info` dictionary using `literal_eval()`, therefore: `tuple([int(n) for n in version.split('.')])` is not interpreted and crashes. That's the reason why I thought extending the usability of `version_pattern` will be great!
