### ISSUE TITLE
set: -l: invalid option

### ISSUE THREAD

**Issue by jenstroeger** [relekang/python-semantic-release#398]
## The problem

Looking through the Action log:

![semrel](https://user-images.githubusercontent.com/12053937/142284097-517c6a3d-9468-48c3-a739-09533fe17cf4.jpg)

See also the [docs for `set`](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html).

## Expected behavior

Not sure what `-l` was supposed to do here?

**Comment by relekang** [comment]
This is fixed now
