### ISSUE TITLE
error: 404 Not Found: 404 in semantic-release publish

### ISSUE THREAD

**Issue by jonathanstelter** [relekang/python-semantic-release#407]
## The problem

Semantic-release publish fails after posting the changelog to Gitlab. _error: 404 Not Found: 404_ is raised. However, new versions are bumped and new commits and the changelog are pushed as expected.

## Expected behavior

The error is occuring for several weeks. Everything worked as expected before.

## Additional context

We use semantic-release integrated in Gitlab CI pipelines for several large projects. The error is occuring for all of the projects and is causing pipeline failures.

**Comment by jacco-oosterhuis** [comment]
I have the same issue on gitlab when pushing and having semantic-release-publish do it's magic:
Pushing new version
Posting changelog to HVCS
error: 404 Not Found: 404
After that though, semantic release does manage to update the version, create a tag, and push to git, in separate pipelines. 
Any idea how I can resolve this (possibly false) error?

**Comment by relekang** [comment]
Please post [debug logs](https://python-semantic-release.readthedocs.io/en/latest/troubleshooting.html#debug-usage) if this is still a problem
