### ISSUE TITLE
Tip of current branch is behind remote counterpart

### ISSUE THREAD

**Issue by jacco-oosterhuis** [relekang/python-semantic-release#415]
Hi, we are trying to use semantic release in gitlab ci but the semantic-release script seems to fail. It runs and is able to publish to the remote repository if executing semantic-release publish locally. However, when "semantic-release publish" is part of the gitlab ci

```
release_notes:
  stage: doc
  script:
    - semantic-release publish
```
(git token is set as variable)
we get the following error message

error:  ! [rejected]        feature_semantic_release -> feature_semantic_release (non-fast-forward)
error: error: failed to push some refs to [repo]
error: hint: Updates were rejected because the tip of your current branch is behind
error: hint: its remote counterpart. Integrate the remote changes (e.g.
error: hint: 'git pull ...') before pushing again.
error: hint: See the 'Note about fast-forwards' in 'git push --help' for details.' 

our config file:

```
[semantic_release]
version_variable = modulename/version.py:VERSION 
upload_to_repository = false
hvcs = gitlab
hvcs_domain = [our repo]
branch = feature_semantic_release
```
Any idea what causes this error? (It only happens when pushing and when semantic-release publish is part of the gitlab ci)
Thanks!

**Comment by carlfischerjba** [comment]
I think this is the same as #414. Try adding the variable `GIT_STRATEGY: clone` in your job so that GitLab CI runner does a full clone instead of a lightweight fetch.

**Comment by jacco-oosterhuis** [comment]
Thanks, that fixed that issue! There are still other errors arising "error: The verification check for the environment did not pass" but I will try separately to fix these.
