### ISSUE TITLE
Change commit message prefix

### ISSUE THREAD

**Issue by sagigvili** [relekang/python-semantic-release#418]
Hi,
I would like to change the 'fix' 'minor' and 'major' prefix in commit message which change the version to another prefix, for example:
'fix' --> 'bug'
'minor' --> 'feature'
'major' --> 'update'

I tried to understand from the documentaion but couldn't understand how, is it really possible?
If it does, can someone provide an example?

Thanks!

**Comment by yturgema1** [comment]
great question faced with the same few days ago would like to know how to handle it...

**Comment by sagigvili** [comment]
Anyone can help?
