### ISSUE TITLE
Make branch a config parameter

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#43]
`master` is currently hard coded several places

**Comment by b3ross** [comment]
It would be great to have this.

**Comment by relekang** [comment]
Yeah, PRs are highly appreciated. 🙂

**Comment by Shadark** [comment]
Sorry for intruding (I don't have a lot of experience with software development, CI systems or semantic versioning), but I think not pushing to `master` branch is the cause of the errors where my version number wouldn't change (I was getting `The verification check for the environment did not pass.` messages and, even if I could push to Pypi, my version number wouldn't change). If this is the case, I wanted to suggest that, if "un-hardcoding" `master` branch references from the code is a difficult task, maybe it could be suggested in the documentation that currently the version number only changes when updating the `master` branch.

Thanks for reading!
