### ISSUE TITLE
committing with --allow-empty

### ISSUE THREAD

**Issue by JamesButler10** [relekang/python-semantic-release#430]
Hi, loving the python-semantic-release generally works really well. I had a question about committing with an empty commit (still including a message).

While getting used to using semantic-release we've sometimes forgotten to add in a `fix:` or `feat:` to the commit message before merging, so obviously no build has occurred. After It's merged we've created a new merge request with no change and run the command `git commit -m 'fix: test empty commit '--allow-empty` . I'd hoped that it would bump the patch number as expected but this has sadly not happened. 
debug traceback:
![image](https://user-images.githubusercontent.com/45291420/160435033-0b1f7ccd-1d4a-4678-8ada-d25bc0d4692c.png)

Is there a better solution for this situation or would it be possible for a change to allow the `--allow-empty` to be implemented.

**Comment by sunnydsouza** [comment]
I would be interested in knowing this as well.
