### ISSUE TITLE
Error when using the package in Giltab hosted in HTTP

### ISSUE THREAD

**Issue by FlorentGodin** [relekang/python-semantic-release#431]
Hi, first, thanks for your great tool!

## The problem

We host GitLab internally and we don't use HTTPS. The problem is that python-semantic-release add automatically "https" at the start of our domain so it crashes (with this error `port 443: Connection refused`)

## Expected behavior

We would like to specify he package to use HTTP instead of HTTPS.

Thanks for your help!

**Comment by relekang** [comment]
Since we send secrets in these requests we I don't think we want to support http
