### ISSUE TITLE
Why is `changelog_placeholder` required?

### ISSUE THREAD

**Issue by mrlubos** [relekang/python-semantic-release#454]
## The problem

*A clear and concise description of what the bug is.*

Perhaps I am misunderstanding this project, but I view it as the Python version of [semantic-release](https://github.com/semantic-release/semantic-release). As such, I expect most things to be the same. One of them is the change log which currently fails if you simply create an empty file.

## Expected behavior

*A short description of what you expected to happen.*

Changelog is written when an empty file exists.

## Additional context

*Add any other information that could be useful, such as your configuration file or an example commit.*

The reason this doesn't work is because there's no placeholder present in an empty file. However, no such placeholder is required in the JavaScript semantic-release project. Plus, it's an extra configuration that could be avoided by having a smart default which is currently missing. Most people will probably want their changelog to write new changes on top, i.e. the same behaviour we achieve by using the placeholder. Therefore, placeholder should be an optional configuration parameter and not required.

**Comment by browniebroke** [comment]
I'm not a maintainer, but I've contributed this feature in #266. It was done this way to be backwards compatible with projects that were already using PSR and maintaining a changelog otherwise. Without the placeholder, we could have written the changes twice.
