### ISSUE TITLE
Name and email for release commit?

### ISSUE THREAD

**Issue by jenstroeger** [relekang/python-semantic-release#473]
I noticed the git user configuration for the semantic release commit for Github Actions:

https://github.com/relekang/python-semantic-release/blob/d7406ef55287c5a4a70e79c63292f5416ab0f00d/action.sh#L15-L21

Curious where the user name and email come from? In [this example](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token) the Github folks seem to recommend
```
          git config user.name github-actions
          git config user.email github-actions@github.com
```
There’s indeed an [actions](https://github.com/actions) org but no [github-actions](https://github.com/github-actions) org, and no email addresses provided for either 🤔

**Comment by jenstroeger** [comment]
@relekang any thoughts?

**Comment by relekang** [comment]
I have no idea where it comes from, but happy to accept a pr with you suggestion.
