### ISSUE TITLE
error: no versions found in the configured locations

### ISSUE THREAD

**Issue by Tyrdall** [relekang/python-semantic-release#478]
## The problem

After updating from 7.29.6 to 7.29.7, we receive an error "no versions found in the configured locations"

## Expected behavior

Version should be found in the given spot.

## Additional context

After downgrading again to 7.29.6, it works fine.
I've tried referencing a variable in a pyproject.toml as well as in a python file.

**Comment by matija94** [comment]
Having same issue here
v7.29.6 works for me as well

**Comment by FirefoxMetzger** [comment]
Same issue on our CI. 

For now, my workaround is to `pip install python-semantic-release!=7.29.7`, but I will try to spend some time later today or tomorrow to investigate where this may come from.

**Comment by FirefoxMetzger** [comment]
This appears to be fixed by 7.30.1 which was released today. At least it is working again on our CI and my local machine. Thank you @eifinger 🚀
