### ISSUE TITLE
version_variable not picked up

### ISSUE THREAD

**Issue by lemoustachiste** [relekang/python-semantic-release#500]
Hey,

I have setup semantic-release in one project and it was fairly straightforward: https://github.com/blockchain-certificates/cert-issuer/blob/master/setup.cfg

Now I am trying to set it up in another project https://github.com/blockchain-certificates/cert-schema/pull/46 with basically the same configuration. However, when running the CI, I am getting the following:

```
$ semantic-release publish --noop --verbosity=DEBUG

debug: get_current_version_by_config_file()

error: must specify either 'version_variable', 'version_pattern' or 'version_toml'
```

But as you can see in the PR, I have set up about the same thing (I tried changing the source file to another but got the same issue), and in the other project it does not fail.

I am not sure how to debug further at this point, is there something obvious I have missed?

**Comment by bernardcooke53** [comment]
Hey @lemoustachiste , I was scratching my head for a minute here, but I think the reason is because PSR only works against a single branch and the default branch is `master`, so although you've added what looks like the right configuration to me, PSR is running `git checkout master` in your CI before attempting to find your version variable (and then it's obviously no longer there).
The checkout takes place [here](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/cli.py#L347) while the bump happens [a bit later](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/cli.py#L374).
It might be an idea to place a check in your CI and if it's not running against `master` then skip PSR :slightly_smiling_face:

**Comment by lemoustachiste** [comment]
Yes, I think you are correct, when I was setting up for the other project I was actually merging into master to get SR to work.
I think I overlooked that part, I somehow expected the dry run to run on the PR branch, but I was rushing things this time.

I think that should solve it

**Comment by lemoustachiste** [comment]
I was too enthusiastic, I've got the same issue after merging to master: https://app.travis-ci.com/github/blockchain-certificates/cert-schema/builds/255497735 (line 1214)

**Comment by bernardcooke53** [comment]
After a bit more head-scratching I have a theory: I don't think PSR can find your `setup.cfg`. It's erroring with only two lines of output even on debug - i.e. it must be getting stuck on [get_current_version](https://github.com/relekang/python-semantic-release/blob/ffae2dc68f7f4bc13c5fd015acd43b457e568ada/semantic_release/cli.py#L315). This function would call [get_current_version_by_tag](https://github.com/relekang/python-semantic-release/blob/ffae2dc68f7f4bc13c5fd015acd43b457e568ada/semantic_release/history/__init__.py#L265) if it was configured properly, but instead it's falling straight to `get_current_version_by_config_file` (which calls `load_version_declarations`, the function with the error being thrown). 

PSR looks for config in `$PWD/pyproject.toml`, followed by merging that with any config in `$PWD/setup.cfg` (settings in the former take precedence). I can see in your [.travis.yml](https://github.com/blockchain-certificates/cert-schema/blob/52e84899751a86e0c475fa562b8c29020741779d/.travis.yml#L15) you have a `cd npm` inside the pipeline - however I couldn't see anything to `cd ..` back to the root of your repo after that (there's some `cd` in and out of another repo, but I suspect this is taking place _inside_ the `npm` directory in your pipeline). I've not used Travis though so I can't confirm, it's just a hunch - would you be able to check/debug what `pwd` and `ls` return just before running `semantic-release publish --noop -v DEBUG`?

**Comment by lemoustachiste** [comment]
That was it, it's always the obvious that does not jump to the eye.

Thanks for the support and I really appreciate the time you spent figuring it out.

**Comment by bernardcooke53** [comment]
Glad I could help :slightly_smiling_face:
