### ISSUE TITLE
Running alongside semantic-release js

### ISSUE THREAD

**Issue by lemoustachiste** [relekang/python-semantic-release#501]
I would like to configure a project that delivers an npm package as well as a python package.
The npm side is configured already and the python side is WIP (see https://github.com/relekang/python-semantic-release/issues/500).

I am running the js semantic release first. So it's the one tagging the github commit. Obviously doing so, I'll have a discrepancy where the python version will be one version ahead since it should pickup the next tag (or will it actually not pick up a new version since it will read from the latest tag 🤔?).

Anyhow, I am wondering if someone has done that before and could guide me on the python SR configuration?

**Comment by bernardcooke53** [comment]
Hey @lemoustachiste , generally I would use one tool or the other to avoid conflicts between them! Is there something specific that PSR does which you can't do with JS?
You would need to watch for the pitfall of invoking the right one - `npx semantic-release` for JS, `semantic-release` for PSR (if I remember correctly the JS version doesn't create a `semantic-release` command line utility and needs to be invoked with `npx`).
It should be possible to turn off tagging/committing/etc with PSR as it is through the various config options, but it might be more overhead than managing the version with the JS semantic-release - bearing in mind that that also does the changelog by default too. Whenever I needed Python metadata managed by the JS version, I would either `json.load` the `package.json` in `setup.py`, or use the [exec plugin](https://github.com/semantic-release/exec) with a `sed` `prepareCmd` for `pyproject.toml` (admittedly a bit hacky but it does the job - works for Rust too if you need to change `Cargo.toml`).

**Comment by lemoustachiste** [comment]
Hi @bernardcooke53,

thanks for your reply. I could indeed actually destructure the JS version to only do the npm release (which is what I'm after) and rely on the python version for the github and pypi update. 

Thanks for the perspective, I'll try that today.

**Comment by bernardcooke53** [comment]
For completeness btw - if the JS version is doing everything _except_ building and publishing a Python package, you'll probably get a bit more flexibility out of using `pip wheel .` and/or `pip install build && build .` (using [build](https://pypa-build.readthedocs.io/en/latest/) for an easy build tool) or equivalent for building, and just running `twine upload` on the command-line for publishing the artefacts (that's in effect what PSR [does with them too](https://github.com/relekang/python-semantic-release/blob/ffae2dc68f7f4bc13c5fd015acd43b457e568ada/semantic_release/repository.py#L163)

**Comment by lemoustachiste** [comment]
Indeed that's another possibility, but I like 2 things with PSR: versioning is done automatically and for the upload part I don't need to configure reading from ENV variables. 

I'll see how things work together with my next release, I might have to adjust then.

Thanks again for the quick support.

**Comment by VegarRingdalAibel** [comment]
Would be nice if we could have a `version_json` option too.
Been trying out this project, and its really nice. 🥇 
Would be nice to use it in other projects (non python) for the release part/set version.

**Comment by AntoninRousset** [comment]
In order to change the version in package.json you can use:
```toml
version_variables = [
  'package.json:"version"',
]
```

**Comment by VegarRingdalAibel** [comment]
@AntoninRousset thank you
