### ISSUE TITLE
Fallback to whole log if correct tag is not available

### ISSUE THREAD

**Issue by relekang** [relekang/python-semantic-release#51]
The log evaluation looks at `v{current_version}...` in some cases(e.g. on a unreleased project). This will not be available. It should fall back to the whole log if that happens and the message generator should stop when it hit a commit containing the current version like it worked before.

**Comment by fattybenji** [comment]
If that is OK with you, I will try taking this one.

**Comment by relekang** [comment]
@fattybenji That would be awesome 👍
