### ISSUE TITLE
Allow global config.

### ISSUE THREAD

**Issue by skorokithakis** [relekang/python-semantic-release#53]
It would be nice if there were a global config file at `~/.config/semantic-release.cfg` or similar that had the lowest priority of all the config files and where we could insert configuration lines.

My use case for this is mainly the `GH_TOKEN`, as storing it in my shell's config is harder to secure. A dedicated config file would be very handy.

**Comment by relekang** [comment]
Sounds like a very good idea. I am a bit short on time these days so I am not sure I can take the time to soon. If you would like to provide a patch, it is very much appreciated.

**Comment by cvockrodt** [comment]
Consider using [appdirs](https://pypi.org/project/appdirs/1.2.0/) for this
