### ISSUE TITLE
Running semantic-release when not in a git repository

### ISSUE THREAD

**Issue by blackHatMonkey** [relekang/python-semantic-release#74]
When running `semantic-release` in a directory which is not a git repository you get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/semantic-release", line 7, in <module>
    from semantic_release.cli import main
  File "/usr/lib/python2.7/site-packages/semantic_release/cli.py", line 9, in <module>
    from .history import (evaluate_version_bump, get_current_version, get_new_version,
  File "/usr/lib/python2.7/site-packages/semantic_release/history/__init__.py", line 6, in <module>
    from ..vcs_helpers import get_commit_log, get_last_version
  File "/usr/lib/python2.7/site-packages/semantic_release/vcs_helpers.py", line 8, in <module>
    repo = Repo('.git', search_parent_directories=True)
  File "/usr/lib/python2.7/site-packages/git/repo/base.py", line 135, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/blackhatmonkey/.git
```
This seems to be an un-caught exception. This also means that you cannot even run `semantic-release --help` when not in a repository.

Perhaps this error should be caught and a more user-friendly error printed on screen. Also I think parsing of the arguments should happen before any operations so you can get at least the help.

**Comment by relekang** [comment]
> Perhaps this error should be caught and a more user-friendly error printed on screen.

Good idea 🙌 

> Also I think parsing of the arguments should happen before any operations so you can get at least the help.

Yes, I agree seems like 
[this line](https://github.com/relekang/python-semantic-release/blob/master/semantic_release/vcs_helpers.py#L8) should be moved into a function instead of being run on import of the vcs_helpers file.

**Comment by blackHatMonkey** [comment]
@relekang So how would you go about solving this?

**Comment by relekang** [comment]
@blackHatMonkey In `vcs_helpers.py` it would be necessary to change line 8:
```python
repo = Repo('.git', search_parent_directories=True)
```

to

```python
def get_repository():
    return Repo('.git', search_parent_directories=True)
```
and then change all usages of the variable to call the function.
