### ISSUE TITLE
Move project to jazzband?

### ISSUE THREAD

**Issue by skorokithakis** [relekang/python-semantic-release#79]
The project seems rather inactive, so I'd like to suggest moving it to the [Jazzband group](https://jazzband.co/), where people can collectively help maintain it. I'm in the group as well and would be willing to help out.

**Comment by relekang** [comment]
Not sure if this it is big enough according to jazzband guidelines.

**Comment by skorokithakis** [comment]
I don't think that would be a problem, you do have happy users :)

**Comment by jezdez** [comment]
Hey @relekang, @skorokithakis asked me to chime in, the size of a project doesn't really matter as long as it follows the guidelines.

That said, @skorokithakis it seems like there have been constant releases, so I'm not sure if you're correct in saying that it's "rather inactive".

Either way, it's up to the maintainer to move a project to Jazzband and should not be taken lightly. @relekang Please let me know if you have questions about the process or Jazzband in general.

**Comment by skorokithakis** [comment]
Yeah, I was going by the commit graph when I made that comment, but @relekang proved to be very responsive. Feel free to close this ticket, I'm happy.

**Comment by relekang** [comment]
@jezdez Nice to hear that this passes the viability section 😅

Anyways, I am a bit reluctant to move it over to jazzband at this moment for mostly for two reasons. The thing that have degraded the most over time is the infrastructure around CI and such things. I don't like the idea of handing over anything without fixing that. Furthermore, there is not much work here in terms of the maintaining. However, I do not spend a lot of time on features now, but PRs are always welcome ✌️
