### ISSUE TITLE
GitPython locked to old version causes PackingType exception

### ISSUE THREAD

**Issue by kevinkjt2000** [relekang/python-semantic-release#80]
My first issue here, so I wanted to say thanks for bringing the loveliness of semantic release to python!

Today I ran into an issue with GitPython that has already been fixed in a newer version https://github.com/gitpython-developers/GitPython/issues/687

It seems that the requirements.txt file here is locking GitPython to an old version.  Any chance that could be updated?

**Comment by relekang** [comment]
Yeah, sure I might be able to do this in the end of the week. If you want it faster a PR is always welcome. :v:

**Comment by relekang** [comment]
Fixed in v3.11.1 thanks to @blackHatMonkey
