### ISSUE TITLE
Use custom parser

### ISSUE THREAD

**Issue by Amoki** [relekang/python-semantic-release#84]
I wrote a custom parser as explained in the doc (http://python-semantic-release.readthedocs.io/en/latest/commit-log-parsing.html#writing-your-own-parser) but the lib can't load my function:
```
semantic_release.errors.ImproperConfigurationError: Unable to import parser "No module named 'semantic_release_config'"
```

Here's my setup 
```cfg
; setup.cfg
[semantic_release]
version_variable=semantic_release_config/__init__.py:__version__
commit_parser=semantic_release_config.parser
```

```
# files:
project_root/
  ├── setup.cfg
  └── semantic_release_config/
       ├── __init__.py
       └── parser.py
```

```python
from .parser import commit_parser as parser
__version__ = '1.0.25'
```

What do I miss ?

Thanks !

**Comment by relekang** [comment]
I think it should be `commit_parser=semantic_release_config:parser` with a colon since it is looking up a function/variable inside the module. The same way looking up the version variable is imported.

**Comment by Amoki** [comment]
https://github.com/relekang/python-semantic-release/blob/6786487ebf4ab481139ef9f43cd74e345debb334/semantic_release/settings.py#L25
The path is split on `.` and imported with `import_module`
Contrary to the version parser (https://github.com/relekang/python-semantic-release/blob/6786487ebf4ab481139ef9f43cd74e345debb334/semantic_release/history/__init__.py#L27) using file open

**Comment by Amoki** [comment]
That it !
I used the default pythonpath. Adding the project directory in the path works !

Thanks !
