### ISSUE TITLE
Publish to PyPI attempts to upload old distributions

### ISSUE THREAD

**Issue by AumitLeon** [relekang/python-semantic-release#86]
I'm getting an error where a new release is being generated properly and is uploaded to PyPI, but 
the CircleCI build step fails because python-semantic-release also attempts to upload older distributions to PyPI. 

The relevant step in the CircleCi workflow: 
```yaml
- run:
      name: upload to pypi
      command: |
          git config --global user.email "aumitleon1@gmail.com"
          git config --global user.name "aumitleon"
          . venv/bin/activate
          semantic-release publish
```

After successfully uploading to the newest version to PyPI (v0.2.5), it also attempts to upload the previous version (v0.2.4), which causes an error:
<img width="1401" alt="screen shot 2018-09-03 at 2 42 59 pm" src="https://user-images.githubusercontent.com/8445744/44998959-bcee9c00-af87-11e8-91e2-34a58b8eb6a6.png">

I suspect the issue has to do with setting `skip_existing` to the `retry` boolean:
https://github.com/relekang/python-semantic-release/blob/762fbcfb72f3ed269eaa1bbb8b0de433166a0a47/semantic_release/cli.py#L156

Is there a reason why `skip_existing` is set to retry? 

From my understanding, the `retry` option just attempts to publish changes using the existing version, without bumping a new version. I don't think the `skip_existing` option for twine should be tied to this boolean because `skip_existing` is meant to avoid uploading any distributions already on PyPI (See: https://github.com/pypa/twine/issues/63), which I believe is the cause of this error. 

I've submitted a PR that I think should resolve this issue. Open to any comments or questions 😃

**Comment by relekang** [comment]
Do we know why it tries to upload old versions?

**Comment by AumitLeon** [comment]
I think so. From what I've seen, if the `retry` flag isn't specified, then `skip_existing` defaults to `False`:
https://github.com/relekang/python-semantic-release/blob/762fbcfb72f3ed269eaa1bbb8b0de433166a0a47/semantic_release/pypi.py#L5

The problem with that is, when a user doesn't specify `retry`, the call to twine sets `skip_existing` to `False` and it attempts to upload old versions. The `skip_existing` flag, when set to true, ensures that twine doesn't attempt to upload older versions (which is what I believe is causing this error). 

When the user does specify `retry`, older distributions are not uploaded because a new release is just generated with the current version. This seems like it's desired behavior, but I think tying `retry` to `skip_existing` misses the case where a user tries to publish a new release without the `retry` flag.

**Comment by relekang** [comment]
What I am trying to ask is I don't understand why it tried to upload the old version when it released a new one? That shouldn't happen regardless of the skip_existing flag. Whenever semantic release is running without retry it should fail if the version that it releases already exist to show that whatever one tried to upload was not uploaded.

**Comment by AumitLeon** [comment]
In my case, my configs are set to upload to PyPI and I'm running `semantic-release publish`. From looking at the function, it seems like the version is evaluated: 
https://github.com/relekang/python-semantic-release/blob/762fbcfb72f3ed269eaa1bbb8b0de433166a0a47/semantic_release/cli.py#L131-L139

Followed by the step that is in charge of the upload to PyPI: 
https://github.com/relekang/python-semantic-release/blob/762fbcfb72f3ed269eaa1bbb8b0de433166a0a47/semantic_release/cli.py#L151-L157

> What I am trying to ask is I don't understand why it tried to upload the old version when it released a new one? That shouldn't happen regardless of the skip_existing flag. 

Please do correct me if I'm wrong (I may be missing some context), but it seems like the reason it's trying to upload the old versions is exactly because of the `skip_existing` flag for the twine upload step. 

When running without `retry`, it first successfully uploads the new version, and then fails when attempting to upload an older version (a duplicate that already exists in PyPI). I think the reason it tries to upload this file is because of the way `skip_existing` is set and it's default value. I'm not sure if this is also true for cases when configs are not set to upload to PyPI. 

But in the case in which `retry` isn't specified, i think `skip_existing` defaults to `False` (as per the `upload_to_pypi` function definition. In my case, I think that the default to False is what prompts the call to twine to attempt to upload older versions. 

There's no explicit check that stops semantic release from uploading an old version because that happens in the call to twine. 

>  Whenever semantic release is running without retry it should fail if the version that it releases already exist to show that whatever one tried to upload was not uploaded.

This happens already, but from the screenshot it's because twine is throwing an error.
