### ISSUE TITLE
PyPi credentials

### ISSUE THREAD

**Issue by Sieboldianus** [relekang/python-semantic-release#99]
First: this is a very nice package, thank you very much for sharing with the world!

After some minor troubles, I got it to work. I have the feeling most of my issues settings things up is because I'm using windows, not Linux, and I am using semantic-release locally, not in CI.

However, I think it makes sense reporting this for other users:

- Formerly, I had my Twine pypi credentials stored in my home directory in a file called `.pypirc`.
- python-semantic-release does not seem to recognize this file. Further, setting Environmental Variables under windows made no difference. I bypassed this for the moment by removing credentials check in `pypi.py` and replacing the upload with `run('twine upload dist/*')` - this would use my .pypirc-file.

There were three other things that want to mention:
- if setting up a new repo with semantic-release, it will fail if no tag is present on first run. The first version-tag must be created manually.
- if both Github and another Gitlab-Remote is used, Push will fail when GH_Token is present because the URL for Github is hardcoded in `hvcs.py` (`DOMAIN = 'https://api.github.com'`)
- changelog seems only to work for Github. It would be awesome to have this create a changelog.md or include changes in minor-major version tags

Not really problems, as said, this is a really fantastic approach.

**Comment by relekang** [comment]
>Formerly, I had my Twine pypi credentials stored in my home directory in a file called .pypirc.
>python-semantic-release does not seem to recognize this file. Further, setting Environmental Variables under windows made no difference. I bypassed this for the moment by removing credentials check in pypi.py and replacing the upload with run('twine upload dist/*') - this would use my .pypirc-file.
There were three other things that want to mention:

I don't get why setting the environment variables does not work. Setting this in the shell works for me on windows:

```
set PYPI_USERNAME="..."
set PYPI_PASSWORD="..."
```

>if setting up a new repo with semantic-release, it will fail if no tag is present on first run. The first version-tag must be created manually.

See #51

> if both Github and another Gitlab-Remote is used, Push will fail when GH_Token is present because the URL for Github is hardcoded in hvcs.py (DOMAIN = 'https://api.github.com')

I am not sure I understand, can you please open a new issue and elaborate?

> changelog seems only to work for Github. It would be awesome to have this create a changelog.md or include changes in minor-major version tags

See #27

**Comment by Sieboldianus** [comment]
Thanks for the prompt reply! I'll test again Environmental variables and report.
As to the other questions: makes sense. I will report Github/Gitlab issue once I had another look at it.

**Comment by Sieboldianus** [comment]
I had a look into password environmental variable:
The problem was that I have a Double Quote in my password, and it is impossible to set the variable from the console with a double quote, apparently double quotes inside quoted strings [cannot be escaped](https://superuser.com/a/962805/710592):

    The fact is, there's nothing that will escape " within quotes for argument passing. You can brood over this for a couple of years and arrive at no solution. This is just some of the inherent limitations of cmd scripting.

The exit code was confusing me, it looked like the information was missing:

    Exit code: 1                                                                                                                                                                                                                                                                                                                                                                                                Stderr:                                                                                                                                                                                                                                                                                                                                                                                                     HTTPError: 403 Client Error: Invalid or non-existent authentication information. for url: https://upload.pypi.org/legacy/
--

I will think of other ways to submit the password.
